### PR TITLE
fix: delete all children and nested children on component delete

### LINKED ISSUE #9168: Deleted components from previous versions reappearing in the latest version
### Description:
An issue is occurring where components deleted in previous versions are reappearing in the latest version. This happens randomly and persists even after deleting the components multiple times.

### Current Behavior:

1. User deletes one or more components in a previous version of the app.
2. User creates a new version of the app.
3. The deleted components unexpectedly reappear in the latest version of the app.
4. User attempts to delete the reappeared components again.
5. Deleted components persist and reappear in the latest version after saving.

### Expected Behavior:

1. User deletes one or more components in a previous version of the app.
2. User creates a new version of the app.
3. The deleted components are permanently removed and do not reappear in the latest version or subsequent versions.
4. User should be able to successfully delete components and have them remain deleted.

### Notes:
1. Thoroughly investigate if this issue affects parent-child components, as well as regular components.

### Attaching a screengrab for reproducing the issue
https://www.loom.com/share/db789bff47df40bca7f1e55980ef19ce?sid=6bd88155-483d-4c44-8b7d-0776c51e69be

### PR DESCRIPTION
**Pull request by johnsoncherian**
Fixes #9168

### CODE REVIEW

File: frontend/src/_helpers/utils.js [hunk 1]
```diff
@@ -1197,3 +1197,37 @@ export const setWindowTitle = async (pageDetails, location) => {
...
+  if (component.component.parent) {
+    const parentComponent = allComponents.find((comp) => comp.id === component.component.parent);
+    /** Certain components have a parent ID assigned but lack an actual parent element on the page, primarily due to past issues or bugs. */
+    if (parentComponent) {
+      return isChildComponentOf(parentComponent, parentId, allComponents);
+    }
+  }
+
+  return false;
+};
```
Comment (kavinvenkatachalam) [inline frontend/src/_helpers/utils.js:1233]: There is a function `getAllChildComponents` returns the child components. Can you try reusing that?

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@johnsoncherian Added a comment. Please merge the PR with latest main

**Review by kavinvenkatachalam — DISMISSED** [review]
