### PR TITLE
Fix event handler name not visible in darkmode

### LINKED ISSUE #837: Event handler name is not legible in dark mode
handler

### PR DESCRIPTION
**Pull request by virajbahulkar**
Fixes #837

### CODE REVIEW

File: frontend/src/Editor/Inspector/EventManager.jsx [hunk 1]
```diff
@@ -257,9 +258,11 @@ export const EventManager = ({
             }}
           >
             <div className={rowClassName} role="button">
-              <div className="col">{componentMeta.events[event.eventId]['displayName']}</div>
               <div className="col">
-                <small className="text-muted">{actionMeta.name}</small>
+                {componentMeta.events[event.eventId]['displayName']}
+              </div>
+              <div className="col">
+                <small className={darkMode ? 'text-warning' : 'text-muted'}>{actionMeta.name}</small>
```
Comment (Navaneeth-pk) [inline frontend/src/Editor/Inspector/EventManager.jsx:265]: Can we handle it in CSS?
eg: `src/_styles/theme.scss:1840`

**Review by Navaneeth-pk — APPROVED** [review]
