### PR TITLE
Fix : Caching the foreign key column options 

### LINKED ISSUE #9745: TJ DB: Foreign Key column options are loaded every time an FK cell is clicked
### What is the expected behaviour?
FK column options should not be loaded every time an FK cell is clicked. Instead, first 10 values should be cached so that user has all the options shown as he opens FK cell options. 
Also, for the red banner inside dropdown need to change copy from "No table selected" to "No values found"

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/144771579/38c96845-1926-4689-8aa4-248ff00b8316

### PR DESCRIPTION
**Pull request by manishkushare**
Resolves #9745

### CODE REVIEW

File: frontend/src/TooljetDatabase/Table/index.jsx [hunk 1]
```diff
@@ -89,6 +89,80 @@ const Table = ({ collapseSidebar }) => {
   const [isCellUpdateInProgress, setIsCellUpdateInProgress] = useState(false);
   const [referencedColumnDetails, setReferencedColumnDetails] = useState([]);
 
+  const [cachedOptions, setCahedOptions] = useState([]);
+
+  const fetchFkDataForColumn = (currentColumn, currentIndex) => {
```
Comment (ganesh8056) [inline frontend/src/TooljetDatabase/Table/index.jsx:94]: can we rename **currentColumn** to **foreignKey** if it is meant to be a foreign key

File: frontend/src/TooljetDatabase/Table/index.jsx [hunk 2]
```diff
@@ -89,6 +89,80 @@ const Table = ({ collapseSidebar }) => {
...
+    // responsible to fetch the fk column details for all available fk's and cache them
+    return new Promise((resolve, reject) => {
+      if (!currentColumn?.referenced_column_names?.length) return resolve();
```
Comment (ganesh8056) [inline frontend/src/TooljetDatabase/Table/index.jsx:97]: Rather than checking `currentColumn?.referenced_table_id,` on line 104 should we check here

File: frontend/src/TooljetDatabase/Table/index.jsx [hunk 3]
```diff
@@ -89,6 +89,80 @@ const Table = ({ collapseSidebar }) => {
...
+
+  const fetchAllFkData = async () => {
+    const dataToCache = {};
+
+    const results = await Promise.allSettled(
+      foreignKeys.map((currentColumn, currentIndex) => fetchFkDataForColumn(currentColumn, currentIndex))
+    );
+
+    results.forEach((result, index) => {
+      console.log('kiran ::', { result });
```
Comment (ganesh8056) [inline frontend/src/TooljetDatabase/Table/index.jsx:147]: could you remove the console log

File: frontend/src/TooljetDatabase/Table/index.jsx [hunk 4]
```diff
@@ -89,6 +89,80 @@ const Table = ({ collapseSidebar }) => {
   const [isCellUpdateInProgress, setIsCellUpdateInProgress] = useState(false);
   const [referencedColumnDetails, setReferencedColumnDetails] = useState([]);
 
+  const [cachedOptions, setCahedOptions] = useState([]);
```
Comment (ganesh8056) [inline frontend/src/TooljetDatabase/Table/index.jsx:92]: Since cached options are **Object** by default `const dataToCache = {};` as mentioned in line no 140. Can we make cachedOptions default state as empty object.

**Review by akshaysasidrn — CHANGES_REQUESTED** [review]

**Review by akshaysasidrn — APPROVED** [review]
