### PR TITLE
Bug fixed : dark theme issues

### LINKED ISSUE #3437: [Multiselect widget] Label text not clearly visible in dark mode
### What is the expected behaviour?

The color of the label text of the Multiselect widget should change to dark color.

### What is the current behaviour?

The color of the label text of the Multiselect widget remains white in dark mode.

### How to reproduce the issue?

1. Toggle on dark mode and open the app editor
2. Drag multiselect widget on the canvas
3. The label will not be clearly visible 

### Screenshots or Screencast
Screenshot 2022-06-29 at 5 01 09 PM

### LINKED ISSUE #3993: Bug : [ File Picker widget ] is not consistent with the dark theme
### Environment
Development

### What is the expected behaviour?
The Filepicker widget should be consistent with the dark theme

### What is the current behaviour?
The Filepicker widget is not consistent with the dark theme. In a dark theme, when no files are selected and files are selected, in both cases, text color is not going well with the dark theme

### How to reproduce the issue?

1. Create a new application or open an existing app
2. Switch to a dark theme, by clicking on the half moon icon at the bottom of the left sidebar. (Please skip step 2, if the app is in dark theme by default)
3. Drag Filepicker widget in the canvas from the right sidebar. (You can also search for it, using the search box at the top of the right sidebar)
4. You can see, the File Picker widget on the canvas, when no files are selected, you can see the text, **Drag and Drop some files here, or click to select files**, its color is not going well with a dark theme.
5. Click inside the File Picker widget, and a window will pop up to select a file, select any file and upload it.
6. You can see the uploaded file now in the file picker widget, see its text color is also not going well with the dark theme.

### Screenshots or Screencast
[Tooljet - Dashboard - 8 September 2022 - Watch Video](https://www.loom.com/share/1986859feb284c6ab705b1810ad764fd)

### Any possible solutions?
change the text color

### Can you identify the location in the driver source code where the problem exists?
frontend > src > Editor > Cmponents > FilePicker.jsx

### If the bug is confirmed, would you be willing to submit a PR?
Yes

### LINKED ISSUE #3999: Bug : [ Map Widget ] is not consistent with the dark theme
### Environment
Development

### What is the expected behaviour?
The Map widget should be consistent with the dark theme

### What is the current behaviour?
The Map widget is not consistent with the dark theme. The search box is not consistent with the dark theme.

### How to reproduce the issue?

1. Create a new application or open an existing app
2. Switch to a dark theme, by clicking on the half moon icon at the bottom of the left sidebar. (Please skip step 2, if the app is in dark theme by default)
3. Drag Map widget on the canvas from the right sidebar. (You can also search for it, using the search box at the top of the right sidebar)
4. You can see the Map widget on the canvas.
5. A pop-up should be open inside the Map, just click OK.
6. You can see Map clearly after clicking on the OK button, and observe, that the search box is not consistent with the dark theme.

### Screenshots or Screencast
Screenshot 2022-09-09 at 5 21 28 PM

### Any possible solutions?
Make the search box background color to dark theme and text color to be white in dark theme.

### Can you identify the location in the driver source code where the problem exists?
frontend > src > Editor > Components > Map.jsx

### If the bug is confirmed, would you be willing to submit a PR?
Yes

### LINKED ISSUE #4000: Bug : [ Steps widget ] is not consistent with dark theme.
### Environment
Development

### What is the expected behaviour?
The Steps widget should be consistent with the dark theme.

### What is the current behaviour?
The steps widget is not consistent with the dark theme.  default text color is not going well with the dark theme.

### How to reproduce the issue?

1. Create a new application or open an existing app
2. Switch to a dark theme, by clicking on the half moon icon at the bottom of the left sidebar. (Please skip step 2, if the app is in dark theme by default)
3. Drag the Steps widget on the canvas from the right sidebar. (You can also search for it, using the search box at the top of the right sidebar)
4. You can see the Steps widget on the canvas.
5. Observe default text color of the steps is not going well with the dark theme.

### Screenshots or Screencast
Screenshot 2022-09-09 at 5 33 07 PM

### Any possible solutions?
1. We can change the default text color from `widget.config` to black color.  
2. Now in Map.jsx, add the condition if the text color is black by default and the dark theme is applied, then change it color to white, otherwise, apply whatever text color is coming from the prop.

### Can you identify the location in the driver source code where the problem exists?
1. frontend > src > Editor > COmponents > Steps.jsx
2. widget.config

### If the bug is confirmed, would you be willing to submit a PR?
Yes

### LINKED ISSUE #4001: Bug :  [ Right sidebar ] search box and label tag in the widget inspector is not consistent with the dark theme.
### Environment
Development

### What is the expected behaviour?
The Right sidebar should be consistent with the dark theme, along with the widget inspector 

### What is the current behaviour?
The right sidebar should be consistent with the dark theme, along with the widget inspector 

### How to reproduce the issue?

1. Create a new app or open an existing one
2. Observe the right sidebar, at the top of the right sidebar, a search box is there, which is not consistent with the dark theme. That's our first issue.
3. Now, Drag any widget from the right sidebar on the canvas. and click on the label of that widget on the canvas itself. (A widget inspector will appear in the right sidebar itself. )
4. In the widget inspector, label tags are not consistent with the dark theme.

### Screenshots or Screencast
Screenshot 2022-08-29 at 7 44 37 PM
Screenshot 2022-09-09 at 5 49 51 PM

### Any possible solutions?
1. Change the color of the label tag to a white shade in a dark theme (it  will be more readable )
2 . Change the placeholder color in the dark theme.

### If the bug is confirmed, would you be willing to submit a PR?
Yes

### LINKED ISSUE #4002: Bug : [ Event Manager ] is not consistent with the dark theme when, action is selected as Go to App
### Environment
Development

### What is the expected behaviour?
The event Management pop-up should be consistent with the dark theme

### What is the current behaviour?
The event Management pop-up is not consistent with the dark theme. When we select action as **Go to App** in the event management pop-up, the App dropdown appears under the action option, observe the dropdown, it is not consistent with the dark theme.

### How to reproduce the issue?

1. Create a new application or open an existing one
2. Switch to a dark theme, by clicking on the half moon icon at the left sidebar. (Please avoid step 2 if, the application is already in a dark theme.)
3. Drag any widget on the canvas ( for eg - Button).
4. On Canvas, click on the label of the widget, which was dragged on canvas. A widget inspector will be seen in the right sidebar.
5. In the widget inspector, look for the event section, if no events are added, then added an event by clicking on **+add event handler** in the same section.
6. A event button will appear in the event section, click on it.
7. A event manager pop-up will appear. For the **action** label, select the **Go to App** option in the dropdown.
8.  When Go to App is selected,  another dropdown gets added below the action option column, open it and observe it is not consistent with the dark theme. That's our main issue now.
9. Also, the action dropdown and app dropdown seems to overlap each other.

### Screenshots or Screencast
1. App dropdown is not consistent with the dark theme.
Screenshot 2022-09-09 at 6 42 02 PM

2. App and action dropdown overlap each other
Screenshot 2022-09-09 at 6 42 52 PM

### If the bug is confirmed, would you be willing to submit a PR?
Yes

### LINKED ISSUE #4003: Bug : Input placeholder at some places in the application are not consistent with the dark theme.
### Environment
Development

### What is the expected behaviour?
The input placeholder should be consistent with the dark theme.

### What is the current behaviour?
The input placeholder at the following places in the application is not consistent with the dark theme. Font color is not readable in the dark theme.
1. placeholder for select search component.
2. Search box on the Homepage

### How to reproduce the issue?

The search box on the Homepage

1. Login into ToolJet, and you will be redirected to Home Page.
2. Switch to a dark theme by clicking on the half moon icon in the Header section. (Ignore step 2, if you are already in a dark theme)
3. Observe, a placeholder in the search box on the Home page itself, it's not going well with a dark theme. We can make it more readable, by changing its color to close to white shade.

Select search component (custom dropdown component)
1. for example, Create a new app
2. Switch to a dark theme, by clicking on the half moon icon present at the bottom of the left sidebar. (Ignore step 2 , if already in the dark theme.)
3. Drag the Table widget on the canvas.
4. Open the Table widget inspector by clicking on the label of the widget on the canvas.
5. You can see the widget inspector for the table in the right sidebar.  Look for the Column section, and click on any one of the columns present in that section.
6. A pop-up will appear, in the pop-up, look for column type, it will have one dropdown as an input field. Its placeholder is not consistent with the dark theme.

### Screenshots or Screencast
Screenshot 2022-09-09 at 7 15 52 PM

Screenshot 2022-09-09 at 7 15 52 PM

### If the bug is confirmed, would you be willing to submit a PR?
Yes

### LINKED ISSUE #4004: Bug : Organization avatar and profile avatar is not consistent with the dark theme.
### Environment
Development

### What is the expected behaviour?
The organization avatar and profile avatar on the Headers on the Home page should be consistent with the dark theme.

### What is the current behaviour?
The organization avatar and profile avatar on the Headers on the Home page is not consistent with the dark theme.

### How to reproduce the issue?

1. Login into ToolJet Account. You will be redirected to the Home Page.
2. Switch to a dark theme, by clicking on the half moon icon, present in the header section. (Ignore step 2, if already in dark theme)
3. On the Home page, on the rightmost side of the headers section, look for the Organization avatar and profile avatar. They are not consistent with the dark theme.

### Screenshots or Screencast
Screenshot 2022-09-09 at 7 26 06 PM

### If the bug is confirmed, would you be willing to submit a PR?
Yes

### LINKED ISSUE #4005: Bug : Modal to share the app is not consistent with the dark theme.
### Environment
Development

### What is the expected behaviour?
Modal to share the application should be consistent with the dark theme.

### What is the current behaviour?
Modal to share the application is not consistent with the dark theme. The embeddable link to the share app is not visible in the dark theme.

### How to reproduce the issue?

1. Create a new application or open an existing application
2. Switch to a dark theme by clicking on the half moon icon at the bottom of the left sidebar. (Please ignore step 2, if already in dark theme)
3. Click on the Share button present on the right side of the header section.
4. A modal will open at the center of the window. Look for **Get the embeddable link for this application**, you can see below it, that the text area is not readable in the dark theme.

### Screenshots or Screencast

Screenshot 2022-09-09 at 8 02 28 PM

### If the bug is confirmed, would you be willing to submit a PR?
Yes

### LINKED ISSUE #4007: Bug : Footer in the Home Page is not consistent with the dark theme.
### Environment
Development

### What is the expected behaviour?
The footer on the homepage should be consistent with the dark theme

### What is the current behaviour?
The footer on the homepage is not consistent with the dark theme.

### How to reproduce the issue?

1. Login into ToolJet 
2. You will be redirected to Home Page. 
3. Switch to a dark theme by clicking on the half moon icon in the Header section. (Please ignore step 2, if you are already in dark theme)
4. Observe the footer on the Homepage, the text color of content on the left side of the footer is not going well with the dark theme.

### Screenshots or Screencast
Screenshot 2022-09-09 at 9 50 48 PM

### Any possible solutions?
Change the text color in the dark theme.

### If the bug is confirmed, would you be willing to submit a PR?
Yes

### LINKED ISSUE #4008: Bug : [ Chart widget inspector ] typo error, unwanted comma present in inspector
### Environment
Development
### What is the expected behaviour?
There should be no typo error as a such present.

### What is the current behaviour?
In the Chart Inspector component, an unwanted comma is present, which is causing a typo error

### How to reproduce the issue?

1. Create a new application or open an existing one 
2. Drag the Chart widget on the canvas from the right sidebar.
3. Click on the label on the Chart widget which is dragged on the canvas, to open a  Chart widget inspector
4. Scroll down in the widget inspector and look for the Options section. In the Options section, just above the show grid line, there is an unwanted comma present. We have to remove that.

### Screenshots or Screencast
Screenshot 2022-09-09 at 10 03 17 PM

### Any possible solutions?
Remove the unwanted comma

### Can you identify the location in the driver source code where the problem exists?
frontend/src/Editor/Inspector/Components/Chart.jsx

### If the bug is confirmed, would you be willing to submit a PR?
Yes

### PR DESCRIPTION
**Pull request by manishkushare**
1. File Picker  -  Resolves #3993
2. Map widget - Resolves  #3999
3. Steps Widget - Resolves  #4000
4. Multiselect widget label  - Resolves #3437
5. Search bar in widget manager and label tag in widget inspector - Resolves #4001
6. Event Manager, when Go to the app is selected as action - Resolves #4002
7. Search box (placeholder )on the homepage and select-search (placeholder) component specific - Resolves #4003
8. Organization and profile avatar - Resolves #4004
9. Modal for share application - Resolves #4005
10. Footer on the Home Page - Resolves #4007
11. Typo error, unwanted comma in Chart widget inspector - Resolves #4008

### CODE REVIEW

**Comment by shubh22** [comment]
Task linked: [CU-2tm4vnj Dark theme fixes](https://app.clickup.com/t/2tm4vnj)

File: frontend/src/_components/SearchBox.jsx [hunk 1]
```diff
@@ -2,7 +2,7 @@ import React, { useState, useEffect } from 'react';
 import PropTypes from 'prop-types';
 import useDebounce from '@/_hooks/useDebounce';
 
-export function SearchBox({ width = '200px', onSubmit, debounceDelay = 300 }) {
+export function SearchBox({ width = '200px', onSubmit, debounceDelay = 300, darkMode = undefined }) {
```
Comment (kavinvenkatachalam) [inline frontend/src/_components/SearchBox.jsx:5]:
```suggestion
export function SearchBox({ width = '200px', onSubmit, debounceDelay = 300, darkMode = false }) {
```

Instead of undefined, we can have it as false

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
Few minor issues noticed,

1. Search text is not visible in the darkMode on multi-select
image
2. When I search the location in the map in the darkMode and if I delete the widget, I can see the white line in the canvas
image

**Review by kavinvenkatachalam — APPROVED** [review]
