### PR TITLE
[bugfix] Fixed single workspace organization menu issue

### LINKED ISSUE #4338: Organization menu didn't show for non-admin users in single workspace mode
### Version Information
Latest
### Environment

All

### What is the current behaviour?

The organization menu didn't show for non-admin users in single workspace mode
### How to reproduce the issue?

1. Create a new user in a single workspace instance 
2. log in to the new user's workspace & observe

### If the bug is confirmed, would you be willing to submit a PR?
Yes

### PR DESCRIPTION
**Pull request by shah21**
Resolves #4338

### CODE REVIEW

File: frontend/src/_components/Organization.jsx [hunk 1]
```diff
@@ -325,10 +325,14 @@ export const Organization = function Organization({ darkMode }) {
...
         </a>
-        {(!isSingleOrganization || admin) && (
+        {!isSingleOrganization || admin ? (
           <div className="dropdown-menu end-0" data-cy="workspace-dropdown">
             {isListOrganizations ? getListOrganizations() : getOrganizationMenu()}
           </div>
+        ) : (
+          <div className="dropdown-menu end-0" data-cy="workspace-dropdown">
+            {getOrganizationMenu()}
+          </div>
```
Comment (gsmithun4) [inline frontend/src/_components/Organization.jsx:335]:
```suggestion
        
          <div className="dropdown-menu end-0" data-cy="workspace-dropdown">
            {!isSingleOrganization || admin ? (isListOrganizations ? getListOrganizations() : getOrganizationMenu()) : getOrganizationMenu()}
          </div>
```

**Review by gsmithun4 — CHANGES_REQUESTED** [review]

**Review by gsmithun4 — APPROVED** [review]
