### PR TITLE
fix: add transition to search input

### LINKED ISSUE #2717: Transition animation for app search field on the dashboard
image
When this field is clicked, the width is increased. It would be better if we add `ease-in-out` transition for width change. 

Reference: https://stackoverflow.com/questions/7861648/animate-an-elements-width-from-0-to-100-with-it-and-its-wrapper-being-only-a

### PR DESCRIPTION
**Pull request by Olaleye-Blessing**
resolve #2717

### CODE REVIEW

File: frontend/src/_ui/Search/Search.jsx [hunk 1]
```diff
@@ -95,6 +95,7 @@ export const SearchBox = ({ onChange, ...restProps }) => {
           onChange={handleChange}
           className="form-control"
           placeholder={placeholder ?? 'Search'}
+          style={{transition: "width 0.2s ease-in-out"}}
```
Comment (Navaneeth-pk) [inline frontend/src/_ui/Search/Search.jsx:98]: Can we use a class instead of inline CSS? If we can abstract these styles into a class like `animate-width-change`, we can  reuse it for other input fields in future if we want to.

**Comment by Olaleye-Blessing** [comment]
@Navaneeth-pk I tried creating a class but I couldn't find the base css file.

**Comment by Olaleye-Blessing** [comment]
@Navaneeth-pk I've seen the [base styles folder](https://github.com/ToolJet/ToolJet/tree/develop/frontend/src/_styles). Should create an util file and add the class to it?

**Review by Navaneeth-pk — APPROVED** [review]
