### PR TITLE
Enhancement: Replacing react-select-search library for event managers with react-select library

### LINKED ISSUE #3228: Enhancement request : Replace 'react-select-search' with 'react-select' library in Event Manager component
### Environment
Development

### What is the expected behavior?
In the event Manger, the dropdown should be visible entirely or its height should get adjusted accordingly, so as not to overflow

### What is the current behavior?
When the event manager is at the bottom of the display, the dropdown goes out of the flow and its height is not adjusted accordingly to avoid it.

### How to reproduce the issue?

1. Drag any widget (add date picker widget)
2. Open the Widget Inspector by clicking on the dragged widget label
3. Click on + add event handlers ---> event will get added 
4. Click on that added event, and a pop-up window will get displayed
5. Click on `Show Alert` input, a dropdown will appear, and you can see the dropdown goes out of the flow

### Screenshots or Screencast

Screenshot 2022-06-08 at 8 11 36 PM

### Any possible solutions?
Replace the react-select-search library with react-select as it is much more convenient and set `useMenuPortal` prop to true

### PR DESCRIPTION
**Pull request by manishkushare**
Resolve #3228

### CODE REVIEW

File: frontend/src/Editor/Inspector/EventManager.jsx [hunk 1]
```diff
@@ -1,11 +1,13 @@
-import React, { useState } from 'react';
+import React, { useEffect, useState } from 'react';
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/Inspector/EventManager.jsx:1]: `useEffect` can be removed as it is not used anywhere in the file

File: frontend/src/Editor/Inspector/EventManager.jsx [hunk 2]
```diff
@@ -1,11 +1,13 @@
...
 import { ActionTypes } from '../ActionTypes';
 import OverlayTrigger from 'react-bootstrap/OverlayTrigger';
 import Popover from 'react-bootstrap/Popover';
-import SelectSearch, { fuzzySearch } from 'react-select-search';
 import { CodeHinter } from '../CodeBuilder/CodeHinter';
 import { GotoApp } from './ActionConfigurationPanels/GotoApp';
+import Select from '../../_ui/Select';
+import defaultStyles from '../../_ui/Select/styles';
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/Inspector/EventManager.jsx:8]: For better readability, we can import using `@`

```suggestion
import Select from '@/_ui/Select';
import defaultStyles from '@/_ui/Select/styles';
```

File: frontend/src/Editor/Inspector/EventManager.jsx [hunk 3]
```diff
@@ -131,14 +133,24 @@ export const EventManager = ({
...
+                  ...styles,
+                  menuPortal: (provided) => ({ ...provided, zIndex: 9999 }),
+                  menuList: (base) => ({
+                    ...base,
+                    '::-webkit-scrollbar': {
+                      width: '2px',
+                    },
+                  }),
+                }}
+                useMenuPortal="true"
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/Inspector/EventManager.jsx:153]: Instead of string, `bool` value can be passed
```suggestion
                useMenuPortal={true}
```

File: frontend/src/Editor/Inspector/EventManager.jsx [hunk 4]
```diff
@@ -147,14 +159,24 @@ export const EventManager = ({
...
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/Inspector/EventManager.jsx:179]: Same here
```suggestion
                useMenuPortal={true}
```

File: frontend/src/Editor/Inspector/EventManager.jsx [hunk 5]
```diff
@@ -186,14 +208,24 @@ export const EventManager = ({
...
+                        ...styles,
+                        menuPortal: (provided) => ({ ...provided, zIndex: 9999 }),
+                        menuList: (base) => ({
+                          ...base,
+                          '::-webkit-scrollbar': {
+                            width: '2px',
+                          },
+                        }),
+                      }}
+                      useMenuPortal="true"
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/Inspector/EventManager.jsx:228]:
```suggestion
                      useMenuPortal={true}
```

File: frontend/src/Editor/Inspector/EventManager.jsx [hunk 6]
```diff
@@ -227,16 +259,26 @@ export const EventManager = ({
...
+                      ...styles,
+                      menuPortal: (provided) => ({ ...provided, zIndex: 9999 }),
+                      menuList: (base) => ({
+                        ...base,
+                        '::-webkit-scrollbar': {
+                          width: '2px',
+                        },
+                      }),
+                    }}
+                    useMenuPortal="true"
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/Inspector/EventManager.jsx:281]:
```suggestion
                    useMenuPortal={true}
```

File: frontend/src/Editor/Inspector/EventManager.jsx [hunk 7]
```diff
@@ -378,16 +450,26 @@ export const EventManager = ({
...
+                        ...styles,
+                        menuPortal: (provided) => ({ ...provided, zIndex: 9999 }),
+                        menuList: (base) => ({
+                          ...base,
+                          '::-webkit-scrollbar': {
+                            width: '2px',
+                          },
+                        }),
+                      }}
+                      useMenuPortal="true"
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/Inspector/EventManager.jsx:472]:
```suggestion
                      useMenuPortal={true}
```

File: frontend/src/Editor/Inspector/EventManager.jsx [hunk 8]
```diff
@@ -342,8 +404,18 @@ export const EventManager = ({
...
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/Inspector/EventManager.jsx:418]:
```suggestion
                      useMenuPortal={true}
```

File: frontend/src/Editor/Inspector/EventManager.jsx [hunk 9]
```diff
@@ -289,8 +341,18 @@ export const EventManager = ({
...
+                      ...styles,
+                      menuPortal: (provided) => ({ ...provided, zIndex: 9999 }),
+                      menuList: (base) => ({
+                        ...base,
+                        '::-webkit-scrollbar': {
+                          width: '2px',
+                        },
+                      }),
+                    }}
+                    useMenuPortal="true"
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/Inspector/EventManager.jsx:355]:
```suggestion
                    useMenuPortal={true}
```

File: frontend/src/Editor/Inspector/EventManager.jsx [hunk 10]
```diff
@@ -246,16 +288,26 @@ export const EventManager = ({
...
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/Inspector/EventManager.jsx:310]:
```suggestion
                    useMenuPortal={true}
```

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@manishkushare Suggested a few changes

File: frontend/src/Editor/Inspector/EventManager.jsx (hunk 10 above)
Comment (manishkushare) [reply frontend/src/Editor/Inspector/EventManager.jsx]: @kavinvenkatachalam Updated the required changes

**Review by kavinvenkatachalam — DISMISSED** [review]
LGTM

File: frontend/src/Editor/Inspector/EventManager.jsx [hunk 11]
```diff
@@ -186,14 +207,24 @@ export const EventManager = ({
...
-                    <SelectSearch
+                    <Select
                       className={`${darkMode ? 'select-search-dark' : 'select-search'}`}
                       options={alertOptions}
                       value={event.alertType}
                       search={false}
                       onChange={(value) => handlerChanged(index, 'alertType', value)}
-                      filterOptions={fuzzySearch}
                       placeholder="Select.."
+                      styles={{
```
Comment (Navaneeth-pk) [inline frontend/src/Editor/Inspector/EventManager.jsx:217]: Same styles are being repeated at multiple places. Can we create a CSS class for this?

**Review by kavinvenkatachalam — DISMISSED** [review]

**Review by sherfin94 — CHANGES_REQUESTED** [review]
@manishkushare , as you can see, when I select an option from any of the dropdowns, the event manager itself closes. This affects the UX seriously. Perhaps try to call `stopPropagation` on the click event of the dropdown to prevent this from happening. Consult with Gandharv if you're are not able to figure out how to stop the propagation of mouse events.

https://user-images.githubusercontent.com/20333972/173775336-b0df6624-9315-4497-a7d7-78d38084b1ab.mov

**Review by sherfin94 — APPROVED** [review]
