### PR TITLE
made confirm page scrollable

### LINKED ISSUE #2704: Sign up page not scrollable
### What is the expected behaviour?
The sign up page is not scrollable at all

### What is the current behaviour?
The sign up page should be scrollable.
Ps- It gets scrollable if you refresh.

### How to reproduce the issue?

1. Go to the sign up page.
2. Enter your email address and click sign up.
3. Click on the link in the email.
4. Try to scroll & observe

### PR DESCRIPTION
**Pull request by manishkushare**
Resolve #2704

### CODE REVIEW

File: frontend/src/ConfirmationPage/ConfirmationPage.jsx [hunk 1]
```diff
@@ -82,6 +89,7 @@ class ConfirmationPage extends React.Component {
       'Product Manager',
       'Other',
     ];
+    window.addEventListener('resize', this.handleResize);
```
Comment (gondar00) [inline frontend/src/ConfirmationPage/ConfirmationPage.jsx:92]: This isn't he right place to add a event listener please add a event listener inside `componentDidMount` and you need to run a cleanup function which removes the event listener inside `componentWillUnmount` lifecycle methods

Comment (manishkushare) [reply frontend/src/ConfirmationPage/ConfirmationPage.jsx]: Thanks. Made the changes

File: frontend/src/ConfirmationPage/ConfirmationPage.jsx [hunk 2]
```diff
@@ -10,15 +10,27 @@ class ConfirmationPage extends React.Component {
     this.state = {
       isLoading: false,
       newSignup: queryString.parse(props.location.state.search).signup,
+      // windowInnerHeight: window.innerHeight,
```
Comment (Navaneeth-pk) [inline frontend/src/ConfirmationPage/ConfirmationPage.jsx:13]: Please remove unused code instead of commenting,

**Review by Navaneeth-pk — APPROVED** [review]
