### PR TITLE
[Bugfix] On dispatching Undo ⌘Z or Redo ⌘+shift+Z actions to a component on the editor should also update the internal state or props for the children.

### LINKED ISSUE #2825: On dispatching **Undo** `⌘Z` or **Redo** `⌘+shift+Z` actions to a component on the editor should also update the internal state or props for the children.
### Description
On dispatching **Undo** `⌘Z` or **Redo** `⌘+shift+Z` actions to a component on the editor should also update the internal state or props for the children.
Similarly renaming a widget, should also start a new render pass. 

### What is the expected behaviour?
Perform **Undo** `⌘Z` or **Redo** `⌘+shift+Z` actions or rename a widget should update the internal state **currentState** (which is passed down as props to the children)

### What is the current behaviour?
No updates are received to children until the next render, on performing the above actions in the editor.

### How to reproduce the issue?
Case 1: Performing **Undo-ing** or **Redo-ing** action
1. Create a new app from the Dashboard 
2. Click on the **Inspector** from the left sidebar to open the popup. (expand the **component** node )
3. Add a new widget to the canvas from the widget manager. (The widget is added to the inspector popup: in the **component** node )
4. Delete the widget from the editor. The widget should also be removed from the inspector popup
5. Perform an **Undo** action by doing `⌘` + `Z`. The widget (recently deleted) should be back in the editor.
6. Check the inspector popup, the recently deleted widget should be added back to the component node

Case 2: Renaming a widget from the widget inspector
1. Create a new app from the Dashboard 
2. Click on the **Inspector** from the left sidebar to open the popup. (expand the **component** node )
3. Add a new widget to the canvas from the widget manager. For example: a Button widget. Default name is **button1** (The widget is added to the inspector popup: in the **component** node )
```json
component: {
 ...,
 button1: {...}
}
```
4. Click on the **config handler** of the widget to open the widget inspector.
5. Rename the widget to `renamedBtn`. And Press enter. The widget gets the update.
6. Check the inspector popup, the component node should also receive the update and the widget should be renamed to **renamedBtn** from **button1**.

### Screenshots or Screencast

https://user-images.githubusercontent.com/67645175/163368216-cad73017-9aa5-4476-8dca-b6dba17d7b81.mov

### PR DESCRIPTION
**Pull request by arpitnath**
Resolves #2825

### CODE REVIEW

**Review by Navaneeth-pk — APPROVED** [review]

File: frontend/src/Editor/Editor.jsx [hunk 1]
```diff
@@ -144,6 +144,12 @@ class Editor extends React.Component {
     });
   }
 
+  componentDidUpdate(prevProps, prevState) {
+    if (prevState.appDefinition !== this.state.appDefinition) {
```
Comment (gondar00) [inline frontend/src/Editor/Editor.jsx:148]: @arpitnath this doesn't do a deep equality check, 

```
var a = {x: { a: 2 }}
var b = {x: { a: 2 }}

a === b // returns false
```

Can we use lodash's `isEqual` here?
