### PR TITLE
Bugfix :: Making app "create new version"  dropdown into a scrollable container

### LINKED ISSUE #2464: Bugfix :: Creating multiple version lead to a large vertical dropdown in app " create new version " dropdown
### What is the expected behaviour?
To make a fixed container which is scrollable .

### What is the current behaviour?
Creating more number of app version leads to a large vertical popup.

### How to reproduce the issue?

1.Open a new application.
2.Create multiple version for same app.
3.Observe above behaviour.

### Any possible solutions?
Make a fixed height scrollable container.

### If the bug is confirmed, would you be willing to submit a PR?
yes

### PR DESCRIPTION
**Pull request by stepinfwd**
resolve #2464

### CODE REVIEW

**Review by Navaneeth-pk — APPROVED** [review]

File: frontend/src/Editor/AppVersionsManager.jsx [hunk 1]
```diff
@@ -160,7 +164,7 @@ const CreateVersionModal = function CreateVersionModal({
     <Modal
       show={showModal || showCreateVersionModalPrompt}
       setShow={setShowModal}
-      title="Create Version"
+      title="Create sssVersion"
```
Comment (Navaneeth-pk) [inline frontend/src/Editor/AppVersionsManager.jsx:167]: Typo.

**Review by Navaneeth-pk — APPROVED** [review]
