### PR TITLE
Fixed typo in app builder empty canvas text

### LINKED ISSUE #5995: Fix typo in app builder empty canvas text
### What is the current behaviour?
When you create a new application on ToolJet, the canvas has a text says:
```
You haven't added any components yet. Drag components from the right sidebar and drop here. Check out our guide on adding widgets.
```

### What is the expected behaviour?
Rename the widgets to components
```
You haven't added any components yet. Drag components from the right sidebar and drop here. Check out our guide on adding components.
```

### How to reproduce the issue?

1. Create a new application
2. Check the text on the center of the canvas

Screenshot 2023-04-11 at 3 58 36 PM

### PR DESCRIPTION
**Pull request by LalitChauhan27**
Fixed typo in app builder empty canvas text

Fixes #5995

### CODE REVIEW

File: frontend/src/Editor/Container.jsx [hunk 1]
```diff
@@ -335,7 +335,7 @@ export const Container = ({
     }
   }
 
-  React.useEffect(() => {}, [selectedComponents]);
+  React.useEffect(() => { }, [selectedComponents]);
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/Container.jsx:338]: @LalitChauhan27 Can you revert this change? It might throw an error on lint
```suggestion
  React.useEffect(() => {}, [selectedComponents]);
```

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@LalitChauhan27 Thanks for the PR.

Requested a minor change

**Comment by LalitChauhan27** [comment]
> @LalitChauhan27 Thanks for the PR.
> 
> Requested a minor change

Hey @kavinvenkatachalam, I've made the changes that you have mentioned. Can you please review it now?

**Review by kavinvenkatachalam — DISMISSED** [review]

**Comment by LalitChauhan27** [comment]
https://github.com/ToolJet/ToolJet/issues/5995#issuecomment-1504827722

Hey @kavinvenkatachalam, I've fixed few more typos mentioned in the above attachment. Please review my latest commit and let me know if any more changes are required.
PFA

**Review by kavinvenkatachalam — APPROVED** [review]
