### PR TITLE
fix: cell edit modal closes when "enter" key is pressed for number fields

### LINKED ISSUE #8803: Edit modal closes when "enter" key is pressed for number fields
### What is the expected behaviour?
The edit modal should not close with the "Enter" Key.

### What is the current behaviour?
After editing the number field able to close the edit modal by hitting the "Enter" Key.

### How to reproduce the issue?

1. Login with valid credentials
2. Create a table with valid data
3. Navigate to the integer data cell 
4. Press 'Enter' key to edit the selected cell and update the cell 
5. Hit 'Enter'key again

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/59684099/ddd991d6-ebae-42fd-ab7a-a693d3e471ea

### PR DESCRIPTION
**Pull request by ganesh8056**
In ToolJet database cell edit modal closes when "enter" key is pressed for number fields. Ideally, only when there is a change in the value it should trigger the save event.

closes #8803 #8869

### CODE REVIEW

File: frontend/src/TooljetDatabase/Menu/CellEditMenu/index.jsx [hunk 1]
```diff
@@ -78,7 +78,7 @@ export const CellEditMenu = ({
       closePopover();
     }
 
-    if (e.key === 'Enter' && cellValue !== previousCellValue && show) {
+    if (e.key === 'Enter' && cellValue != previousCellValue && show) {
```
Comment (akshaysasidrn) [inline frontend/src/TooljetDatabase/Menu/CellEditMenu/index.jsx:81]: is this change necessary?

File: frontend/src/TooljetDatabase/Forms/EditColumnForm.jsx [hunk 2]
```diff
@@ -196,19 +195,15 @@ const ColumnForm = ({ onClose, selectedColumn, setColumns }) => {
...
-                : 'form-control'
-            }
+            className={'form-control'}
             data-cy="default-value-input-field"
             autoComplete="off"
             onChange={(e) => setDefaultValue(e.target.value)}
             disabled={dataType === 'serial'}
           />
-          {isNotNull === true && (defaultValue?.length <= 0 || defaultValue === null) ? (
+          {/* {isNotNull === true && (defaultValue?.length <= 0 || defaultValue === null) ? (
```
Comment (akshaysasidrn) [inline frontend/src/TooljetDatabase/Forms/EditColumnForm.jsx:204]: remove comments please

**Review by akshaysasidrn — CHANGES_REQUESTED** [review]

**Review by akshaysasidrn — APPROVED** [review]
