### PR TITLE
Read file as dataURL or textString

### LINKED ISSUE #1405: File Picker Incorrectly encodes binary data
### Environment
Docker

### What is the expected behaviour?
Being able to decode binary payloads

### What is the current behaviour?
reader.readAsText breaks binary files.

### How to reproduce the issue?
Use filepicker.file as value in post request.

### Any possible solutions?
Use base64 encoding or provide option to send file as form data.

### Can you identify the location in the driver source code where the problem exists?
Proposed crude fix in Editor/Components/FilePicker.jsx
```
reader.readAsDataURL(acceptedFile); # line 113 currently reads as text

content: zippedResults[0].srcElement.result.split(',')[1], # line 118 split data:binary data url part
```

### If the bug is confirmed, would you be willing to submit a PR?
Yes.

### PR DESCRIPTION
**Pull request by arpitnath**
Fixes #1405 

app: https://tooljetpr-app.herokuapp.com/apps/96d4ea14-6223-4127-b751-d1184e2e8c36

Screenshots/Screencast:
Screenshot 2021-11-16 at 4 53 51 PM
Screenshot 2021-11-16 at 4 59 20 PM

https://www.loom.com/share/4f51052e88de44e9a4917c45ff1cf672

### CODE REVIEW

File: frontend/src/Editor/Components/FilePicker.jsx [hunk 1]
```diff
@@ -95,6 +96,47 @@ export const FilePicker = ({ width, height, component, currentState, onComponent
...
+    const readFileAsText = await getFileData(file);
+
+    // * readAsDataURL
+    const readFileAsDataURL = await getFileData(file, 'readAsDataURL');
+
+    return {
+      name: file.name,
+      type: file.type,
+      content: readFileAsText,
+      data: readFileAsDataURL,
```
Comment (akshaysasidrn) [inline frontend/src/Editor/Components/FilePicker.jsx:136]: I'm thinking about whether it will be better to expose this field as dataUrl instead of data itself such that we don't split result when doing using `readAsDataURL` method. The reasoning being users can use it directly without any preprocessing. Wdyt?

File: frontend/src/Editor/Components/components.js [hunk 2]
```diff
@@ -1166,7 +1166,7 @@ export const componentTypes = [
       disabledState: { type: 'code', displayName: 'Disable' },
     },
     exposedVariables: {
-      file: [{ name: [], content: [], type: [] }],
+      file: [{ name: [], content: '', data: '', type: '' }],
```
[the remark this answers is not in the document]
Comment (arpitnath) [reply frontend/src/Editor/Components/components.js:1169]: yeah name should be string 👍🏻

File: frontend/src/Editor/Components/FilePicker.jsx (hunk 1 above)
Comment (arpitnath) [reply frontend/src/Editor/Components/FilePicker.jsx:136]: yeah, dataURL makes sense

**Review by akshaysasidrn — APPROVED** [review]
Looks good!

**Comment by arpitnath** [comment]
Have removed the app

**Review by Navaneeth-pk — APPROVED** [review]
