### PR TITLE
Fixed empty error logs on debugger

### LINKED ISSUE #7435: RunJs and RunPy query error messages are not showing in debugger logs.
### What is the expected behaviour?

  whenever a runjs or runpy query fails the error message needs to displayed in debugger logs.

### What is the current behaviour?

  The runjs or runpy query's error messages are not showing in debugger logs.

### How to reproduce the issue?

1.Create App add Add runpy query
2.just click run button and click debugger icon to see logs
3.you can see the error messages are empty.

### PR DESCRIPTION
**Pull request by S-Abdul-Rahman**
Fixed #7435

### CODE REVIEW

File: frontend/src/Editor/LeftSidebar/SidebarDebugger/Logs.jsx [hunk 1]
```diff
@@ -13,10 +13,10 @@ function Logs({ logProps, idx }) {
...
       ? logProps?.message
       : logProps?.isQuerySuccessLog
-      ? 'Completed'
-      : logProps?.type === 'component'
-      ? `Invalid property detected: ${logProps?.message}.`
-      : `${startCase(logProps?.type)} failed: ${logProps?.message ?? ''}`;
+        ? 'Completed'
+        : logProps?.type === 'component'
+          ? `Invalid property detected: ${logProps?.message}.`
+          : `${startCase(logProps?.type)} failed: ${logProps?.message === undefined ? logProps?.error?.message : logProps?.message}`;
```
Comment (johnsoncherian) [inline frontend/src/Editor/LeftSidebar/SidebarDebugger/Logs.jsx:19]: Should we check for other falsy values as well.?
```
logProps?.message ? logProps?.error?.message : logProps?.message
```

Comment (S-Abdul-Rahman) [reply frontend/src/Editor/LeftSidebar/SidebarDebugger/Logs.jsx:19]: > Should we check for other falsy values as well.?
> 
> ```
> logProps?.message ? logProps?.error?.message : logProps?.message
> ```

yes, we can check for other falsy values also like this
logProps?.message ? logProps?.message : logProps?.error?.message

**Review by johnsoncherian — APPROVED** [review]
