### PR TITLE
Fix while copy pasting single or multiple components, the component overlaps after the 2nd paste.

### LINKED ISSUE #11061: Copy pasting a single component
### Problem 
While copy pasting a single component, the component overlaps after the 2nd paste. This makes it inconvenient to find out where the component got pasted.

### Suggested Solution
1. User should be able to click on a grid on canvas and paste it that location.
2. If the user does not choose a paste location, the default paste location of the component should not over lap any other component, and be in the vicinity of the copied component.
3. Default paste location for a component inside a container component should be inside the same container component.

### To be checked
Check for issues with copy pasting on an http server - provide proper error message to the developer regarding the issue

### PR DESCRIPTION
**Pull request by nakulnagargade**
Resolves #11061.

### CODE REVIEW

File: frontend/src/AppBuilder/AppCanvas/Grid/gridUtils.js [hunk 1]
```diff
@@ -308,8 +308,8 @@ export function getMouseDistanceFromParentDiv(event, id, parentWidgetType) {
   return { top, left };
 }
 
-export function findHighestLevelofSelection() {
-  const selectedComponents = useStore.getState().getSelectedComponentsDefinition();
+export function findHighestLevelofSelection(_selectedComponents) {
+  const selectedComponents = _selectedComponents || useStore.getState().getSelectedComponentsDefinition();
```
Comment (TooljetBot) [inline frontend/src/AppBuilder/AppCanvas/Grid/gridUtils.js:312]: <div>


<div id="suggestion">
<div id="issue"><b>Consider adding parameter type validation</b></div>
<div id="fix">

Consider adding parameter type validation for `_selectedComponents`. The function may receive unexpected data types which could cause runtime errors.
</div>
<details>
<summary>
<b>Code suggestion</b>
</summary>
<div id="code">

```
 @@ -311,2 +311,5 @@
  export function findHighestLevelofSelection(_selectedComponents) {
 +  if (_selectedComponents && !Array.isArray(_selectedComponents)) {
 +    throw new Error('_selectedComponents must be an array when provided');
 +  }
    const selectedComponents = _selectedComponents || useStore.getState().getSelectedComponentsDefinition();
```
</div>
</details>
</div>


<small><i>Code Review Run <a href=https://github.com/ToolJet/ToolJet/pull/11514#issuecomment-2521286676>#926959</a></i></small>
</div>

---
Is this a valid issue, or was it incorrectly flagged by the Agent?
- [ ] it was incorrectly flagged

File: frontend/src/AppBuilder/_stores/slices/componentsSlice.js [hunk 2]
```diff
@@ -853,11 +854,9 @@ export const createComponentsSlice = (set, get) => ({
           false,
           'addComponentToCurrentPage'
         );
-        if (index === 0) {
-          //incase of multiple components, only first one will be selected since it will be the parent component
-          get().setSelectedComponents([newComponent.id]);
-        }
       });
+      const selectedComponents = findHighestLevelofSelection(newComponents);
+      get().setSelectedComponents(selectedComponents.map((component) => component.id));
```
Comment (TooljetBot) [inline frontend/src/AppBuilder/_stores/slices/componentsSlice.js:859]: <div>


<div id="suggestion">
<div id="issue"><b>Consider validating newComponents array input</b></div>
<div id="fix">

Consider validating the `newComponents` array before accessing it to avoid potential runtime errors if it's undefined or empty.
</div>
<details>
<summary>
<b>Code suggestion</b>
</summary>
<div id="code">

```
 @@ -858,2 +858,5 @@
 +      if (!Array.isArray(newComponents) || newComponents.length === 0) {
 +        return;
 +      }
        const selectedComponents = findHighestLevelofSelection(newComponents);
        get().setSelectedComponents(selectedComponents.map((component) => component.id));
```
</div>
</details>
</div>


<small><i>Code Review Run <a href=https://github.com/ToolJet/ToolJet/pull/11514#issuecomment-2521286676>#926959</a></i></small>
</div>

---
Is this a valid issue, or was it incorrectly flagged by the Agent?
- [ ] it was incorrectly flagged

File: frontend/src/AppBuilder/AppCanvas/Grid/Grid.jsx [hunk 3]
```diff
@@ -354,6 +355,27 @@ export default function Grid({ gridWidth, currentLayout }) {
...
+        const rect = realCanvas.getBoundingClientRect();
+        const x = e.clientX - rect.left;
+        const y = e.clientY - rect.top;
+        setLastClickPosition({ x, y });
+      }
+    },
+    [setLastClickPosition]
+  );
+
+  useEffect(() => {
```
Comment (johnsoncherian) [inline frontend/src/AppBuilder/AppCanvas/Grid/Grid.jsx:371]: can we add this as onClick attribute int real canvas itself?

Comment (nakulnagargade) [reply frontend/src/AppBuilder/AppCanvas/Grid/Grid.jsx]: Yes, added onClick to real-canvas

**Review by johnsoncherian — APPROVED** [review]

**Review by johnsoncherian — APPROVED** [review]
