### PR TITLE
fix: Only one of the events trigger when multiple events with debounce is created

### LINKED ISSUE #8164: When multiple events with debounce is created only one of them trigger
### What is the expected behaviour?
All the events shoukd trigger with proper debounce

### What is the current behaviour?
When every event has debounce only of them trigger

### How to reproduce the issue?

1.Create multiple event with debounce values
2.Observe

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/31006028/4e9d35e5-2733-40e9-89e3-4b6e5e767f87

### If the bug is confirmed, would you be willing to submit a PR?
Yes

### PR DESCRIPTION
**Pull request by stepinfwd**
closes #8164 8164

### CODE REVIEW

File: frontend/src/_helpers/appUtils.js [hunk 1]
```diff
@@ -384,16 +384,24 @@ function logoutAction() {
 }
 
 function debounce(func) {
-  let timer;
+  const timers = new Map();
+
   return (...args) => {
     const event = args[1] || {};
+    const eventId = JSON.stringify(event) + '_' + Date.now(); // Append timestamp
```
Comment (kavinvenkatachalam) [inline frontend/src/_helpers/appUtils.js:391]: can we use `uuid()` instead of stringify and combine with date?

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@stepinfwd Requested a small change. Rest looks good to me

**Review by kavinvenkatachalam — APPROVED** [review]
