### PR TITLE
Bug Fix :Date Picker event not firing the correct parameters.

### LINKED ISSUE #3667: Bug :  Date Picker event not firing the correct parameters
### Environment
Development

### What is the expected behavior?
When we apply any event on Datepicker, on firing that event, we should get the currently selected date

### What is the current behavior?
When we apply any event on Datepicker, on firing that event, we are getting the previously selected date

### How to reproduce the issue?
1. Drag the Datepicker on the canvas
2. Open the Datepicker widget inspector by clicking on the widget's label, which we drag onto the canvas
3. On the left side, we can see the widget inspector for Datepicker, scroll down to search for the events section
4. Set any event. For example - onSelect, we will alert the date picker value. To get the value of datepicker, you can access it as `{{components.datepicker1.value}}`
5. Now fire the event, by selecting the date on the date picker widget on the canvas
6. You can see, the alert message for the date, but the date is inappropriate, it shows a previously selected date in the alert message

### PR DESCRIPTION
**Pull request by manishkushare**
Resolve #3667

### CODE REVIEW

**Comment by shubh22** [comment]
Task linked: [CU-2khd5qx Date Picker event not firing the correct parameters.](https://app.clickup.com/t/2khd5qx)

File: frontend/src/Editor/Components/Datepicker.jsx [hunk 1]
```diff
@@ -36,10 +36,11 @@ export const Datepicker = function Datepicker({
   };
 
   const onDateChange = (date) => {
-    fireEvent('onSelect');
     setDate(date);
     const dateString = computeDateString(date);
-    setExposedVariable('value', dateString);
+    setExposedVariable('value', dateString).then(() => {
+      fireEvent('onSelect');
```
Comment (sherfin94) [inline frontend/src/Editor/Components/Datepicker.jsx:42]: @manishkushare , letting you know that we fire the event on the then function, not on the next line.

**Review by sherfin94 — APPROVED** [review]
