### PR TITLE
bug fixed : changeSet getting updated without changing the value in the table

### LINKED ISSUE #6728: [ Table ] : save / discard button is accessible even if we the cell value is not changed upon on blur
### Version Information
v2.6.2
### Environment
Development

### What is the expected behaviour?
When any column is editable in the table, in that particular column when clicking inside the particular cell, and instead of changing any value, we simply drag the mouse away from it (without making any changes in value), then changeSet should not get updated, and thus save and discard button should not be accessible.

### What is the current behaviour?
In the above-mentioned scenario for column-type text, even if we don't change the value inside the cell, still change set gets updated and thus save and discard button is accessible even if the value is not edited.

### How to reproduce the issue?
1. Create a new app.
2. Drag a table from the right sidebar onto the canvas
3. Now click anywhere on the table to open the table widget inspector in the right sidebar itself.
4. Look for the columns section and click on any one of the cards in the section to open its settings pop-up window.
5. In that window, change the respective type of column to text
6. Now, on that canvas, click inside any cell from that particular column whose type is changed to text and then move away the cursor from that particular cell, as soon as you did that, you can see the save and discard button being accessible. Those buttons are only accessible if we edit the value in any one if the cell

### Screenshots or Screencast
[My app 1686754744072 - Tooljet - 14 June 2023 - Watch Video](https://www.loom.com/share/d220160cb0e14ffe9f362fdd96db6227)

### If the bug is confirmed, would you be willing to submit a PR?
Yes

### PR DESCRIPTION
**Pull request by manishkushare**
Resolves #6728

### CODE REVIEW

File: frontend/src/Editor/Components/Table/columns/index.jsx [hunk 1]
```diff
@@ -164,7 +164,10 @@ export default function generateColumnsData({
                       }
                     }}
                     onBlur={(e) => {
-                      if (e.target.defaultValue !== e.target.value) {
+                      if (
+                        e.target.defaultValue !== e.target.value &&
+                        e.target.defaultValue.replace(/\n/g, '') !== e.target.value // do we require this, I have a doubt, need to add this condition, only when we change the column data type to string from text
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/Components/Table/columns/index.jsx:169]: I checked for the string and default datatype. Seems we're getting the right value and this can be removed

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@manishkushare Added a comment. Let me know if there is any concern

**Review by kavinvenkatachalam — APPROVED** [review]
