### PR TITLE
Foreign key dropdown added for cell edit

### LINKED ISSUE #9748: On TJ DB Dashboard, need to show FKR options in dropdown just below the cell
### What is the expected behaviour?
Need to show FKR values just as in the following designs
image

### What is the current behaviour?

Current, user clicks on cell, then clicks on dropdown inside of cell, clicks to select a value, dropdown closes, then saves it.

### How to reproduce the issue?

1. Create 2 tables
2. Add an FK relation
3. Populate target table and source with data
4. On the dashboard, try to edit a FK cell.

### PR DESCRIPTION
**Pull request by shaurya-sharma064**
closes #9748 

Foreign Key Dropdown added for Cell Edit

### CODE REVIEW

File: frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DropDownSelect.jsx [hunk 1]
```diff
@@ -46,17 +46,32 @@ const DropDownSelect = ({
...
+  isForeignKeyInEditCell,
+  shouldCloseFkMenu,
+  closeFKMenu,
+  saveFKValue,
 }) => {
   const popoverId = useRef(`dd-select-${uuidv4()}`);
   const popoverBtnId = useRef(`dd-select-btn-${uuidv4()}`);
-  const [showMenu, setShowMenu] = useShowPopover(false, `#${popoverId.current}`, `#${popoverBtnId.current}`);
+  const [showMenu, setShowMenu] = useShowPopover(
+    isForeignKeyInEditCell ? true : false,
```
Comment (akshaysasidrn) [inline frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DropDownSelect.jsx:58]: is already a boolean, can skip conditional?

File: frontend/src/TooljetDatabase/Menu/CellEditMenu/index.jsx [hunk 2]
```diff
@@ -149,6 +160,103 @@ export const CellEditMenu = ({
...
+            </div>
+            <div className={`fw-400 ${styles.tjdbCellMenuShortcutsText}`}>Save Changes</div>
+          </div>
+          <div className="d-flex align-items-center gap-1">
+            <div className={`fw-500 ${styles.tjdbCellMenuShortcutsInfo}`}>Esc</div>
+            <div className={`fw-400 ${styles.tjdbCellMenuShortcutsText}`}>Discard Changes</div>
+          </div>
+        </div>
+        <div className="d-flex flex-column align-items-end gap-1">
+          {columnDetails?.constraints_type.is_not_null === false && (
```
Comment (akshaysasidrn) [inline frontend/src/TooljetDatabase/Menu/CellEditMenu/index.jsx:179]: Will column details be missing here? If not can remove optional chain.

**Review by akshaysasidrn — CHANGES_REQUESTED** [review]

**Review by akshaysasidrn — APPROVED** [review]

**Review by akshaysasidrn — APPROVED** [review]
