### PR TITLE
fixed query failed empty toast issue

### LINKED ISSUE #5951: Query toast error never should be empty
### Environment

    ToolJet Cloud / Docker / Linux / MacOS 

### What is the expected behaviour?
- Toast message on query run should not be empty in all the cases.
- The failure message should be meaning full and actionable.

### What is the current behaviour?
Some of the DS queries shows blank toast messages. (only `X` mark)

### How to reproduce the issue?

1. Add a DS
2. Run a query (should be wrong one)
3. Verify the toast

### PR DESCRIPTION
**Pull request by S-Abdul-Rahman**
Fixed #5951 query failed empty toast issue.

### CODE REVIEW

File: frontend/src/_helpers/appUtils.js [hunk 1]
```diff
@@ -1010,7 +1010,7 @@ export function runQuery(_ref, queryId, queryName, confirmed = undefined, mode =
             definition: { events: dataQuery.options.events },
           });
           if (mode !== 'view') {
-            const err = query.kind == 'tooljetdb' ? data?.error || data : _.isEmpty(data.data) ? data : data.data;
+            const err = query.kind == 'tooljetdb' ? data?.error || data : _.isEmpty(data.data) ? data : data;
```
Comment (Ckbhatia) [inline frontend/src/_helpers/appUtils.js:1013]: Why do we need to check `_.isEmpty(data.data)`?

File: frontend/src/_helpers/appUtils.js [hunk 2]
```diff
@@ -1010,8 +1010,8 @@ export function runQuery(_ref, queryId, queryName, confirmed = undefined, mode =
             definition: { events: dataQuery.options.events },
           });
           if (mode !== 'view') {
-            const err = query.kind == 'tooljetdb' ? data?.error || data : _.isEmpty(data.data) ? data : data.data;
-            toast.error(err?.message);
+            const err = query.kind == 'tooljetdb' ? data?.error || data : data;
+            toast.error(err?.message === undefined ? 'Something went wrong' : err?.message)
```
Comment (johnsoncherian) [inline frontend/src/_helpers/appUtils.js:1014]:
```suggestion
            toast.error(err?.message ? 'Something went wrong' : err?.message)
```

Comment (johnsoncherian) [reply frontend/src/_helpers/appUtils.js:1014]: Helps you to check for other falsy values as well

**Review by johnsoncherian — APPROVED** [review]

**Review by johnsoncherian — APPROVED** [review]
