### PR TITLE
[Bigfix] Fixes  edited version's component definition's schema gets altered

### LINKED ISSUE #2640: On realising an app: Edited version's component definition's schema gets altered
### What is the expected behaviour?
The app definition schema should not get altered on changing or creating or deleting new versions nor on releasing the apps.

### What is the current behaviour?
- On realising an app the edited version's component definition schema gets altered, it gets decamalised. 
- Create a new version from the current released version. e.g. new version: v2
- Release v2
- Select v1 and release v1
- Select v2
- App crashes due to component definition's schema alteration to decamelizes the object keys. 

### How to reproduce the issue?

1. Create a new app and set the default version 
2. Add a new widget to the canvas (editor will autosave the changes)
3. Release the app

### Screenshots or Screencast

https://user-images.githubusercontent.com/67645175/160235045-6b0b6f64-233d-41ce-abb0-e864fb1
Screenshot 2022-03-26 at 3 47 31 PM
5d1d3.mp4

### PR DESCRIPTION
**Pull request by arpitnath**
Resolves #2640 

**Loom**
https://www.loom.com/share/4a8ef40eed4949fcba275918ed6be1b1

### CODE REVIEW

**Review by sherfin94 — APPROVED** [review]

File: server/src/controllers/apps.controller.ts [hunk 1]
```diff
@@ -72,6 +72,13 @@ export class AppsController {
     response['data_queries'] = seralizedQueries;
     response['definition'] = app.editingVersion?.definition;
 
+    //! if editing version exits, camalize the definition
```
Comment (akshaysasidrn) [inline server/src/controllers/apps.controller.ts:75]: exists* 
camelize*

**Review by akshaysasidrn — APPROVED** [review]
