### PR TITLE
Fix: resolve double encoding in connection strings

### LINKED ISSUE #15397: [MongoDB]- Need factor for encoding the values passed in connection string
### Environment
LTS-3.16

### What is the expected behaviour?
Need to encode the values passed in connection string 

### What is the current behaviour?
[Connection string]When using %40 (URL-encoded value for @) in the MongoDB password field, it is not being decoded back to @ before authentication. As a result, the system is attempting authentication with the literal value Test%40123 instead of Test@123, which causes an authentication failure.
The password field should either:

Automatically decode URL-encoded characters before use, or
Treat the password input as raw text and avoid double encoding when constructing the connection string.
Currently, %40 is not being converted back to @, leading to incorrect credential handling.

### Screenshots or Screencast

Image

### PR DESCRIPTION
**Pull request by sahil7303**
### Description:
- Safely decode MongoDB credentials to handle edge cases.
- Decode connection string credentials before populating frontend UI fields.

Related issue:
Fixes #15397

### CODE REVIEW

File: plugins/packages/mongodb/lib/index.ts [hunk 1]
```diff
@@ -484,8 +492,8 @@ async getConnection(sourceOptions: SourceOptions): Promise<any> {
 
   if (authPart.includes(":")) {
     const colonIdx = authPart.indexOf(":");
-    connUser = decodeURIComponent(authPart.slice(0, colonIdx));
-    connPass = decodeURIComponent(authPart.slice(colonIdx + 1));
+    connUser = authPart.slice(0, colonIdx);
```
Comment (rudeUltra) [inline plugins/packages/mongodb/lib/index.ts]: decode not required here ?
