### PR TITLE
[Bugfix] Fixes : widgets get focused on viewer mode when hovered

### LINKED ISSUE #2518: Unusual behaviour of widgets on `view` mode
### What is the expected behaviour?
On hover, widgets should only get focused on editor mode.

### What is the current behaviour?
On hover, widgets get focused on viewer mode.

### How to reproduce the issue?

1. Add a dropdown widget from the widget manager
2. Add another widget, e.g., a button.
3. Position the button widget below the dropdown widget
4. Release and Preview the app (will open the app in viewer mode in a new tab)

### Screenshots or Screencast

https://user-images.githubusercontent.com/67645175/158366443-a5faa645-cfb8-43d7-9ed0-d81c4702737b.mov

### PR DESCRIPTION
**Pull request by arpitnath**
Fixes #2518 

### Screenshots or Screencast

https://user-images.githubusercontent.com/67645175/158368189-978c7c90-3edb-4903-af18-debae862640f.mov

### CODE REVIEW

File: frontend/src/Editor/DraggableBox.jsx [hunk 1]
```diff
@@ -188,7 +188,11 @@ export const DraggableBox = function DraggableBox({
     >
       {inCanvas ? (
         <div
-          className={cx(`draggable-box widget-${id}`, { [className]: !!className })}
+          className={cx(
+            `draggable-box widget-${id}`,
+            { [className]: !!className },
+            `${mode === 'edit' ? 'editor' : ''}`
```
Comment (gondar00) [inline frontend/src/Editor/DraggableBox.jsx:194]:
```suggestion
            { [className]: !!className, 'editor': mode === 'edit' }
```

**Review by gondar00 — APPROVED** [review]
