### PR TITLE
Bug Fixed : Success message not displayed clearly in dark mode in advanced option for queries

### LINKED ISSUE #3714: Success message not displayed clearly in dark mode in advanced option for queries
### What is the expected behaviour?
While we type something in the success message then it should be clearly visible in dark mode.

### What is the current behaviour?
While we type something in the success message it is not clearly visible in dark mode.

### How to reproduce the issue?

1. Add any query.
2. Click on dark mode icon.
3. Go to advanced tab.
4. Toogle on show notification on success?
5. Enter something in the success message.

### Screenshots or Screencast
https://drive.google.com/file/d/1-FaAxlfpunoU6LKZ2iWvdzWRX0-R03uB/view?usp=sharing

### PR DESCRIPTION
**Pull request by manishkushare**
Resolves #3714

### CODE REVIEW

**Comment by shubh22** [comment]
Task linked: [CU-2r6akd9 Success message not displayed clearly in dark mode in advanced option for queries](https://app.clickup.com/t/2r6akd9)

File: frontend/src/Editor/QueryManager/QueryManager.jsx [hunk 1]
```diff
@@ -694,8 +694,8 @@ let QueryManager = class QueryManager extends React.Component {
                           currentState={this.props.currentState}
                           initialValue={this.state.options.successMessage}
                           height="36px"
-                          className="form-control"
-                          theme={'default'}
+                          className="form-control p-0"
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/QueryManager/QueryManager.jsx:697]:
```suggestion
                          className="form-control p-1"
```

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@manishkushare The text is not vertically aligned with `p-0`. Can we replace it with `p-1` class?

image

**Review by kavinvenkatachalam — APPROVED** [review]
