### PR TITLE
Bugfix - Custom props are not available in breadcrumbs for certain routes (tooljet-database) 

### LINKED ISSUE #6002: Custom props are not available in breadcrumbs for certain routes (tooljet-database)
## Description
Certain routes where custom props or parameters are not being properly displayed in the breadcrumbs. HTML element resulting in failing in cypress tests

### PR DESCRIPTION
**Pull request by arpitnath**
Resolves #6002

### CODE REVIEW

**Review by kavinvenkatachalam — DISMISSED** [review]

File: frontend/src/_ui/Breadcrumbs/index.jsx [hunk 1]
```diff
@@ -26,7 +27,7 @@ export const Breadcrumbs = () => {
 // define some custom breadcrumbs for certain routes (optional)
 const routes = [
   { path: '/:worspace_id', breadcrumb: 'Apps' },
```
Comment (vikotar) [inline frontend/src/_ui/Breadcrumbs/index.jsx:29]: Hello, @arpitnath. Should we fix the typo here? form `worspace` to  `workspace`? 🤔

Comment (arpitnath) [reply frontend/src/_ui/Breadcrumbs/index.jsx:29]: Yes

**Review by vikotar — APPROVED** [review]

**Review by vikotar — APPROVED** [review]

**Review by akshaysasidrn — APPROVED** [review]

**Review by akshaysasidrn — APPROVED** [review]
