### PR TITLE
Fix: datasource Icons doesn't show on templates model

### LINKED ISSUE #1858: Datasource icons of each template aren't showing on the template model
### Version Information
Latest

### Environment

MacOs

### What is the expected behaviour?

Each template tab should show a data source icon that the template uses. 

### What is the current behaviour?

Now the implementation had been done. but icons don't visible
### How to reproduce the issue?

1. Open template model
2. Switch between templates

### Screenshots or Screencast

Screenshot 2022-01-18 at 1 33 29 PM

### Any possible solutions?
Check if the path is incorrect or not

### If the bug is confirmed, would you be willing to submit a PR?
Yes

### PR DESCRIPTION
**Pull request by shah21**
Fixes #1858

### CODE REVIEW

File: frontend/src/HomePage/TemplateLibraryModal/TemplateDisplay.jsx [hunk 1]
```diff
@@ -1,8 +1,16 @@
 import React from 'react';
 import { Container, Row, Badge } from 'react-bootstrap';
+import { allSvgs } from '@tooljet/plugins/client';
 
 export default function TemplateDisplay(props) {
   const { id, name, description, sources } = props?.app ?? {};
+
+  const getSvgIcon = (key, height = 50, width = 50) => {
```
Comment (Navaneeth-pk) [inline frontend/src/HomePage/TemplateLibraryModal/TemplateDisplay.jsx:8]: Looks like there are other instances of the same function within the app. Can we move it to utils to avoid duplication?

**Review by Navaneeth-pk — APPROVED** [review]
