### PR TITLE
Fix: selection of copy of selected component for ease

### LINKED ISSUE #9016: Selecting the copied component by default when copy pasting components
**Current behavior:**  When copying and pasting components, the parent component remains selected by default, not the copied child component. Attaching a screen grab for reference

**Expected behavior:** After pasting, the copied child component should be automatically selected.
Reasoning: Selecting the copied child component directly after pasting improves accessibility and simplifies further editing.

https://github.com/ToolJet/ToolJet/assets/81761482/c11dce8d-6261-4950-8d6b-e8f21a90c6f1

### PR DESCRIPTION
**Pull request by vjaris42**
resolves #9016

### CODE REVIEW

File: frontend/src/_helpers/appUtils.js [hunk 1]
```diff
@@ -1617,7 +1619,10 @@ export const addComponents = (
   }
 
   updateNewComponents(pageId, appDefinition, finalComponents, appDefinitionChanged, componentMap, isCut);
-  !isCloning && toast.success('Component pasted succesfully');
+  if (!isCloning) {
```
Comment (johnsoncherian) [inline frontend/src/_helpers/appUtils.js:1622]: we can add this behaviour for clonig as well.

**Review by johnsoncherian — APPROVED** [review]
