### PR TITLE
Fixed widget position calculation on resize

### LINKED ISSUE #6905: Components are getting slightly displaced from the grid when they are repositioned or resized
### Environment
Everywhere
### What is the expected behaviour?
When components are resized or repositioned, the borders of the component should always perfectly snap to the grid lines

### What is the current behaviour?
There is slight displacement from the grid lines at times

### How to reproduce the issue?

1. Add two text input components one below the other, in alignment
2. Slight resize the component in the bottom a few times, width wise
3. Resize it back to the same width as the first one
4. Observe the slight difference in width

### PR DESCRIPTION
**Pull request by johnsoncherian**
Fixes #6905

### CODE REVIEW

File: frontend/src/Editor/SubContainer.jsx [hunk 1]
```diff
@@ -383,17 +388,14 @@ export const SubContainer = ({
 
     let { left, top, width, height } = boxes[id]['layouts'][currentLayout] || defaultData;
 
-    const canvasBoundingRect = parentRef.current.getElementsByClassName('real-canvas')[0].getBoundingClientRect();
-    const subContainerWidth = canvasBoundingRect.width;
-
     top = y;
-    if (deltaWidth !== 0) {
+    if (deltaWidth !== 0 && direction === 'left') {
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/SubContainer.jsx:392]:
```suggestion
    if (deltaWidth !== 0 ) {
```

Seems `direction` check is not needed here. Tried without that and working for me

File: frontend/src/Editor/Container.jsx [hunk 2]
```diff
@@ -296,11 +299,15 @@ export const Container = ({
...
+    width = Math.round(width + (deltaWidth * NO_OF_GRIDS) / canvasWidth); // convert the width delta to percentage
     height = height + deltaHeight;
 
     top = y;
-    left = (x * 100) / canvasWidth;
+    if (direction === 'left') {
+      // onResizeStop is triggered for a single click on the border, therefore this conditional logic
+      // should not be removed.
+      left = (x * 100) / canvasWidth;
+    }
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/Container.jsx:310]:
```suggestion
    left = (x * 100) / canvasWidth;
```

Even here the check is not needed

**Review by kavinvenkatachalam — COMMENTED** [review]
@johnsoncherian On the implementation wise it is looks good. Added few suggestions, please check and let me know if I'm wrong

File: frontend/src/Editor/Container.jsx (hunk 2 above)
Comment (johnsoncherian) [reply frontend/src/Editor/Container.jsx:310]: Hi Kavin, Yes feature works without the checks. Added these conditions checks since in these cases the left position of the widget is not expected to change. But we can remove them.

**Review by kavinvenkatachalam — APPROVED** [review]
