### PR TITLE
fixed Text Widget not showing zero and false

### LINKED ISSUE #1651: Text Widget not showing zero and false
### What is the expected behaviour?
Text widget should show any value assigned to it

### What is the current behaviour?
Not showing `0` and `false`

### How to reproduce the issue?

1. Select Text widget
2. Set `Text` as `{{0}}` or `{{false}}`
3. Widget not showing any values

### Screenshots or Screencast
Screenshot 2021-12-28 at 2 27 08 PM

### PR DESCRIPTION
**Pull request by manishkushare**
Resolve #1651

### CODE REVIEW

File: frontend/src/Editor/Components/Text.jsx [hunk 1]
```diff
@@ -5,7 +5,8 @@ export const Text = function Text({ height, properties, styles, darkMode }) {
   const [loadingState, setLoadingState] = useState(false);
 
   const { textColor, textAlign, visibility, disabledState } = styles;
-  const text = properties.text ?? '';
+
+  let text = (properties.text === 0 ? '0' : properties.text === false ? 'false' : properties.text) ?? '';
```
Comment (gsmithun4) [inline frontend/src/Editor/Components/Text.jsx:9]:
```suggestion
  const text = properties.text === 0 || properties.text === false ? properties.text?.toString() : properties.text
```

**Comment by manishkushare** [comment]
Sure, I will update it by the EOD

**Review by gsmithun4 — APPROVED** [review]
LGTM
