### PR TITLE
[ Bugfix ] :: calendar preview is broken when events are added as a result of any query

### LINKED ISSUE #3927: [BUG ]🐛  :: calendar preview is broken when events are added as a result of any query
### What is the expected behaviour?
calendar to be visible while previewing app

### What is the current behaviour?
calendar is broken in app preview if event is added

### How to reproduce the issue?
1) Get event data as a result of any query in calendar
2) Run query on page load
2) Preview this app

Screen Recording 2022-08-31 at 12.56.16 PM.mov

### PR DESCRIPTION
**Pull request by stepinfwd**
closes #3927

### CODE REVIEW

**Comment by shubh22** [comment]
Task linked: [CU-2rx0yd1 calendar preview is broken when events are added as a result of any query](https://app.clickup.com/t/2rx0yd1)

File: frontend/src/Editor/Components/Calendar.jsx [hunk 1]
```diff
@@ -30,8 +30,10 @@ export const Calendar = function ({
 }) {
   const style = { height };
   const resourcesParam = properties.resources?.length === 0 ? {} : { resources: properties.resources };
-
-  const events = properties.events ? properties.events.map((event) => prepareEvent(event, properties.dateFormat)) : [];
+  const events =
+    typeof properties?.events === Array
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/Components/Calendar.jsx:34]:
```suggestion
    Array.isArray(typeof properties?.events)
```

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@stepinfwd `typeof` in the array will always be `object`. To check if it is an array, you can use `Array.isArray()`

**Review by kavinvenkatachalam — APPROVED** [review]
