### PR TITLE
Fix: Autosave definition on version release

### LINKED ISSUE #2119: Releasing version right after upating definition loses last change
### What is the expected behaviour?
The updated changes on the canvas must be saved as the app definition before release

### What is the current behaviour?
Autosave has a debounce of 3s seconds and thus when user releases updated canvas within 3s the changes done will be lost

### How to reproduce the issue?

1. Open editor
2. make change on the editor
3. click on release quickly

### Any possible solutions?
Perform explicit save before releasing version

### If the bug is confirmed, would you be willing to submit a PR?
Yes

### PR DESCRIPTION
**Pull request by akshaysasidrn**
Fixes #2119

### CODE REVIEW

File: frontend/src/Editor/ReleaseVersionButton.jsx [hunk 1]
```diff
@@ -9,11 +9,13 @@ export const ReleaseVersionButton = function DeployVersionButton({
   isVersionReleased,
   fetchApp,
   onVersionRelease,
+  saveEditingVersion,
 }) {
   const [isReleasing, setIsReleasing] = useState(false);
 
   const releaseVersion = (editingVersion) => {
     setIsReleasing(true);
+    saveEditingVersion();
```
Comment (Navaneeth-pk) [inline frontend/src/Editor/ReleaseVersionButton.jsx:18]: Should there be an `await` ?

Comment (akshaysasidrn) [reply frontend/src/Editor/ReleaseVersionButton.jsx:18]: Cant make use await here, as that function comprises of setState calls which don't return promises.
We would have to change this up to handle with multiple callbacks to ensure it runs serially. 

But if I'm not wrong having this run concurrently is fine as one API call is to update the current definition on the canvas and the other to update the current version id and there isn't any dependency on their order of execution.

**Review by Navaneeth-pk — APPROVED** [review]
