### PR TITLE
[Fix] :: Check for subpaths in openapi

### LINKED ISSUE #5022: OpenAPI endpoints get decamelized
### Version Information
v1.30.0

### Environment
Docker / Linux 

### What is the expected behaviour?
An OpenAPI endpoint such as "/Path/With/Uppercase/Names"  should call that path with uppercase path elements preserved.

### What is the current behaviour?
The response from the server get processed by decamelizedKeys()  so the the endpoint becomes "/_p_ath/_w_ith/_u_ppercase/_n_ames".

### How to reproduce the issue?

1. Paste an OpenAPI .json with an endpoint such as "/Path" into create datasource dialog
2. Create query using new datasource.
3. When choosing endpoint the options will show "/_p_ath"

### Can you identify the location in the driver source code where the problem exists?
src/controllers/data_sources.controller.ts:80

### PR DESCRIPTION
**Pull request by vjaris42**
Resolves #5022

### CODE REVIEW

**Review by shah21 — DISMISSED** [review]
LGTM.

File: server/src/controllers/data_sources.controller.ts [hunk 1]
```diff
@@ -56,7 +56,11 @@ export class DataSourcesController {
         );
       }
     }
-    return decamelizeKeys({ data_sources: dataSources });
+    return decamelizeKeys({ data_sources: dataSources }, function (key, convert, options) {
+      //eslint-disable-next-line
```
Comment (gsmithun4) [inline server/src/controllers/data_sources.controller.ts:60]: Shall we add a comment why lint check is disabled?

**Review by gsmithun4 — APPROVED** [review]
