### PR TITLE
Fixed and Modified the popup UI

### LINKED ISSUE #6207: Update the text and UI of `Continue Editing` query popup modal
### What is the current behaviour?

When you edit a query and switch to another query without saving the changes, a modal pops up to continue editing or Discard the query changes. The `Continue editing` button is red, and the `Discard Changes` is white.

### What is the expected behaviour?

Change the text on the popup modal and button placements & color according to the UI below:

Screenshot 2023-05-01 at 7 31 21 PM

### Steps to reproduce
1. Open ToolJet, create a new app
2. Create 2 queries and save them
3. Edit a query1 and switch to query2 without saving the query1
4. A modal will popup

### PR DESCRIPTION
**Pull request by Mohith234**
Fixes #6207

### CODE REVIEW

**Comment by Mohith234** [comment]
@kavinvenkatachalam I have updated both the text and colors of the button. Please review it

File: frontend/src/Editor/Viewer/Confirm.jsx [hunk 1]
```diff
@@ -69,10 +69,10 @@ export function Confirm({
       )}
       <Modal.Body data-cy={'modal-message'}>{message}</Modal.Body>
       <Modal.Footer className="mt-3">
-        <button className="btn" onClick={handleClose} data-cy={'modal-cancel-button'}>
+        <button className="btn btn-danger" onClick={handleClose} data-cy={'modal-cancel-button'}>
           {cancelButtonText === '' ? t('globals.cancel', 'Cancel') : cancelButtonText}
         </button>
-        <button className="btn btn-danger" onClick={handleConfirm} data-cy={'modal-confirm-button'}>
+        <button className="btn" onClick={handleConfirm} data-cy={'modal-confirm-button'}>
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/Viewer/Confirm.jsx:75]: Changing this will affect through out the `Confirm` component wherever it is using. Attaching the screenshot - Delete popup also got affected

image

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@Mohith234 Thanks for the PR. Instead of changing the class, try to change the `confirm` and `cancel` text and callback function where the Confirm component is used.

**Comment by Mohith234** [comment]
@kavinvenkatachalam I need some help with the merge conflicts. Could you please guide me through this?

**Comment by kavinvenkatachalam** [comment]
@Mohith234 It's resolved now. Can you please check it out?

**Review by johnsoncherian — APPROVED** [review]

**Review by johnsoncherian — CHANGES_REQUESTED** [review]
Can we update the message as well according to image in corresponding issue

**Comment by Mohith234** [comment]
Done @johnsoncherian

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@Mohith234 It changed the existing behaviour of other modals. Attaching the screenshots,

**In production -** 

image

**This PR changes -** 
image

Instead of making the changes in `Confirm.jsx`, try to change the data passed to the component. Interchange the confirm text with cancel text and confirm callback with cancel callback. 

cc: @johnsoncherian

**Review by kavinvenkatachalam — APPROVED** [review]

**Review by kavinvenkatachalam — APPROVED** [review]
