### PR TITLE
Tree component is not reflecting data correctly

### LINKED ISSUE #5684: Tree component is not reflecting data correctly
### What is the expected behaviour?

  If user has selected Tree widget component, the data should always appear on the screen

### What is the current behaviour?

  When user selects tree widget, and updates the default content with some syntax error and corrects it back, data is not appearing on the screen, even though the data format is accurate. It is appearing on the screen if user navigates from any other page of the application.

### How to reproduce the issue?

1. Drag tree widget component
2. Change the data structure, add some invalid data/ syntax error. Data will disappear from the screen.
3. Reverse the changes/ correct the data structure
4. As user has updated the structure, data should be displayed again on the screen immediately. Rather it is appearing only when user switches in between different pages and navigates back to the tree widget related page.

### LINKED ISSUE #5774: Tab component visibility related issue
### What is the expected behaviour?

  Tab structure should appear on the screen if user revert the syntax errors.

### What is the current behaviour?

When user selects tab widget, and updates the default content with some syntax error and corrects it back, data is not appearing on the screen, even though the data format is accurate. It is appearing on the screen if user navigates from any other page of the application.

Similar to tree widget related issue.

### How to reproduce the issue?

1. Select Tab component
2. Change the data structure, add some invalid data/ syntax error. Data will disappear from the screen.
3. Reverse the changes/ correct the data structure
4. As user has updated the structure, data should be displayed again on the screen immediately. Rather it is appearing only when user switches in between different pages and navigates back.

### LINKED ISSUE #5789: Steps component visibility related issue
### What is the expected behaviour?

  Provide a clear description of what you want to happen.
Steps component should appear on the screen immediately, if user revert the syntax errors.

### What is the current behaviour?

  Provide a clear description of what is the current behaviour.

When user selects steps widget, and updates the default content with some syntax error and corrects it back, data is not appearing on the screen, even though the data format is accurate. It is appearing on the screen if user navigates from any other page of the application or refresh the application.

### How to reproduce the issue?

1. Select steps component
2. Change the data structure, add some invalid data/ syntax error. Data will disappear from the screen.
3. Reverse the changes/ correct the data structure
4. As user has updated the structure, data should be displayed again on the screen immediately. Rather it is appearing only when user switches in between different pages and navigates back or refreshes the application.

### LINKED ISSUE #5790: Button Groups component visibility related issue
### What is the expected behaviour?

Button groups component should appear on the screen immediately, if user reverts the syntax errors. And the component should be exactly the same as it appears first time when user adds it .

### What is the current behaviour?
When user selects button groups widget, and updates the default content with some syntax error and corrects it back, data is not appearing on the screen, even though the data format is accurate. It is appearing on the screen if user navigates from any other page of the application or refresh the application.

### How to reproduce the issue?

1. Select button groups component
2. Change the data structure, add some invalid data/ syntax error. Some different data will appear on screen.
3. Reverse the changes/ correct the data structure
4. As user has updated the structure, data should be displayed again on the screen immediately. Rather it is appearing only when user switches in between different pages and navigates back or refreshes the application.

### PR DESCRIPTION
**Pull request by manishkushare**
Resolves #5684 
Resolves #5774
Resolves #5789
Resolves #5790
Along with the issues mentioned in the referred issue, tree select has the same behavior, when checekdData and expandedData properties are not valid, this PR addresses those issues as well.

### CODE REVIEW

**Review by kavinvenkatachalam — APPROVED** [review]

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@manishkushare On the tabs widget, I guess the tabs value is already resolved and need not to be resolved again. Can you confirm and if so, can we remove the resolveReferences function call?

**Review by kavinvenkatachalam — DISMISSED** [review]

File: frontend/src/Editor/Components/ButtonGroup.jsx [hunk 1]
```diff
@@ -9,7 +10,11 @@ export const ButtonGroup = function Button({
   darkMode,
   dataCy,
 }) {
-  const { values, labels, label, defaultSelected, multiSelection } = properties;
+  const { label, multiSelection } = properties;
+  const values = isExpectedDataType(properties.values, 'array');
+  const labels = useMemo(() => isExpectedDataType(properties.labels, 'array'), [properties.labels]);
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/Components/ButtonGroup.jsx:15]: Why do we need `useMemo` here?

File: frontend/src/Editor/Components/TreeSelect.jsx [hunk 2]
```diff
@@ -3,14 +3,18 @@ import React, { useState, useEffect, useMemo } from 'react';
 import CheckboxTree from 'react-checkbox-tree';
 // eslint-disable-next-line import/no-unresolved
 import 'react-checkbox-tree/lib/react-checkbox-tree.css';
+import _ from 'lodash';
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/Components/TreeSelect.jsx:6]:
```suggestion
```

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@manishkushare Suggested a few changes. Please take a look

**Review by kavinvenkatachalam — DISMISSED** [review]

**Review by kavinvenkatachalam — APPROVED** [review]
