### PR TITLE
Fixed the typo in event handler screen in page menu

### LINKED ISSUE #5893: Typo in event handler screen in page menu
Screenshot 2023-03-31 at 1 38 58 PM
The text "This query doesnt have any event handlers" should be changed to "This page doesn't have any event handlers"

### PR DESCRIPTION
**Pull request by Avirup-001**
Fixes #5893

### CODE REVIEW

File: frontend/src/Editor/Inspector/EventManager.jsx [hunk 1]
```diff
@@ -862,7 +862,7 @@ export const EventManager = ({
     );
   };
 
-  const componentName = componentMeta.name ? componentMeta.name : 'query';
+  const componentName = componentMeta.name ? componentMeta.name : 'page';
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/Inspector/EventManager.jsx:865]: Changing the text will change the default text in the queries as well. Attaching the screenshot

image

Instead of changing the test, pass the `name` key in the `componentMeta` of the pages `settingsModal.jsx`. 

image

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
Hey @Avirup-001,

Thanks for the PR. 

Made a suggestion. Please check and update the code

File: frontend/src/Editor/Inspector/EventManager.jsx (hunk 1 above)
Comment (Avirup-001) [reply frontend/src/Editor/Inspector/EventManager.jsx]: Thanks for the suggestion @kavinvenkatachalam . Updated it

**Review by kavinvenkatachalam — APPROVED** [review]
