### PR TITLE
[bug-fix] The public app is redirecting to the login page if the user token expired. 

### LINKED ISSUE #5462: The public app is redirecting to the login page when the user token expires
### Version Information
Latest
### Environment

All
### What is the expected behaviour?

Should not redirect to the login page. users should be able to see a public app without authentication 
### What is the current behaviour?

The public app is redirecting to the login page when the user token expires
### How to reproduce the issue?

1. Create an app with queries and make it public (attach any query with some widgets also)
2. release the app. and run the sharable link on a private browser window
3. observe 

### If the bug is confirmed, would you be willing to submit a PR?
Yes

### PR DESCRIPTION
**Pull request by shah21**
Resolves #5462

### CODE REVIEW

File: frontend/src/App/App.jsx [hunk 1]
```diff
@@ -37,6 +37,25 @@ class App extends React.Component {
...
+      // call apps api and get the app type
+      appService.getAppBySlug(paths[length]).then((app) => {
+        if (app && !app.is_public) {
+          if (this.state.currentUser) {
+            this.fetchMetadata();
+          }
+        }
+      });
+    } else {
+      this.fetchMetadata();
```
Comment (gsmithun4) [inline frontend/src/App/App.jsx:55]: Shall we skip the metadata API call if route includes `applications` and add fetch metadata call in app viewer page?
- Advantage of this: we have the app details in app viewer page and can invoke fetch meta call if application is not public

Comment (shah21) [reply frontend/src/App/App.jsx:55]: ok, got it

**Review by gsmithun4 — CHANGES_REQUESTED** [review]
Improvements suggested

**Review by gsmithun4 — APPROVED** [review]

**Review by gsmithun4 — APPROVED** [review]
