### PR TITLE
[ Enhancement ] :: Tabs widget bug fixes

### LINKED ISSUE #2523: [ Enhancement ] :: Tabs widget bugs 🐛
### What is the expected behaviour?

Tab widget enhancements
When we change the default tab field, the change should be  immediately reflected on the widget.
default tab field only accepts string value: make it reflect number values as well
expose the currentTab of tabs widget

### What is the current behaviour?

When we change the default tab field, the change is not immediately reflected on the widget.
Default tab field only accepts string value.
CurrentTab/defaultTab of tabs widget is not exposed.

### How to reproduce the issue?

1.Drag and drop Tabs widget.
2.Observe above issues.

### Can you identify the location in the driver source code where the problem exists?

frontend/src/Editor/Components/Tabs.jsx

### If the bug is confirmed, would you be willing to submit a PR?
Yes 🚀

### PR DESCRIPTION
**Pull request by stepinfwd**
resolves #2523

### CODE REVIEW

File: frontend/src/Editor/Components/Tabs.jsx [hunk 1]
```diff
@@ -42,18 +51,27 @@ export const Tabs = function Tabs({ id, component, width, height, containerProps
   };
 
   const parentRef = useRef(null);
-
+  console.log('parsed tab', parsedDefaultTab);
```
Comment (Navaneeth-pk) [inline frontend/src/Editor/Components/Tabs.jsx:54]: Please remove this line.

File: frontend/src/Editor/Components/components.js [hunk 2]
```diff
@@ -1491,7 +1491,7 @@ export const componentTypes = [
       visibility: { type: 'toggle', displayName: 'Visibility' },
       disabledState: { type: 'toggle', displayName: 'Disable' },
     },
-    exposedVariables: {},
+    exposedVariables: { defaultTab: '' },
```
Comment (Navaneeth-pk) [inline frontend/src/Editor/Components/components.js:1494]: `defaultTab` is the initial tab. I don't think e should change it when the tab is changed.

Comment (stepinfwd) [reply frontend/src/Editor/Components/components.js]: updated @Navaneeth-pk

**Review by sherfin94 — APPROVED** [review]
