### PR TITLE
fix: support workspace constants in OAuth flows

### LINKED ISSUE #15373: Salesforce: While passing workspace constants, no connection could be made.
### Version Information
Version 3.20.101-ee-lts

### What is the expected behaviour?
While passing workspace constants, the connection should be established

### What is the current behaviour?
It was not possible to establish a connection while passing workspace constants.

### How to reproduce the issue?

1. Log in with valid credentials
2. Add a Salesforce data source
3. Use a workspace constant for the client secret

### Screenshots or Screencast
https://jam.dev/c/a0ab050e-171c-4cad-85fa-298bfb7c7c54

### PR DESCRIPTION
**Pull request by sahil7303**
## Summary

This PR fixes an issue where workspace constants (`{{constants.xxx}}` and `{{secrets.xxx}}`) were not being resolved when used in OAuth data source configurations.

#### 1. Auth URL Generation (`getAuthUrl`)
The backend now resolves workspace constants before generating the OAuth URL.

#### 2. Token Exchange (`accessDetailsFrom`)
When saving the data source after OAuth authorization, workspace constants are resolved before token exchange.

### Related Issues
Fixes #15373

### CODE REVIEW

File: server/src/modules/data-sources/controller.ts [hunk 1]
```diff
@@ -126,8 +126,8 @@ export class DataSourcesController implements IDataSourcesController {
   @InitFeature(FEATURE_KEY.GET_OAUTH2_BASE_URL)
   @UseGuards(FeatureAbilityGuard)
   @Post('fetch-oauth2-base-url')
-  getAuthUrl(@Body() getDataSourceOauthUrlDto: GetDataSourceOauthUrlDto) {
-    return this.dataSourcesService.getAuthUrl(getDataSourceOauthUrlDto);
+  getAuthUrl(@User() user: UserEntity, @Body() getDataSourceOauthUrlDto: GetDataSourceOauthUrlDto) {
```
Comment (rudeUltra) [inline server/src/modules/data-sources/controller.ts]: Fetch user from the body, don't change the current controller

File: server/src/modules/data-sources/service.ts [hunk 2]
```diff
@@ -253,8 +253,9 @@ export class DataSourcesService implements IDataSourcesService {
     testDataSourceDto.options = dataSource.options;
     return await this.dataSourcesUtilService.testConnection(testDataSourceDto, user.organizationId);
   }
-  async getAuthUrl(getDataSourceOauthUrlDto: GetDataSourceOauthUrlDto): Promise<{ url: string }> {
-    return this.dataSourcesUtilService.getAuthUrl(getDataSourceOauthUrlDto);
+
+  async getAuthUrl(getDataSourceOauthUrlDto: GetDataSourceOauthUrlDto, user: User): Promise<{ url: string }> {
```
Comment (rudeUltra) [inline server/src/modules/data-sources/service.ts]: same here

File: server/src/modules/data-sources/util.service.ts [hunk 3]
```diff
@@ -146,14 +152,21 @@ export class DataSourcesUtilService implements IDataSourcesUtilService {
       const queryService = await this.pluginsServiceSelector.getService(plugin_id, provider);
 
       // const queryService = new allPlugins[provider]();
+
+      // Resolve workspace constants in options before calling accessDetailsFrom
+      let resolvedOptions = options;
```
Comment (rudeUltra) [inline server/src/modules/data-sources/util.service.ts:157]: make sure the existing options is not getting overriden

File: server/src/modules/data-sources/util.service.ts [hunk 4]
```diff
@@ -192,6 +205,35 @@ export class DataSourcesUtilService implements IDataSourcesUtilService {
     return options;
   }
 
+  /**
+   * Resolves workspace constants in an options array for OAuth token exchange.
+   */
+  protected async resolveOptionsArrayForOAuth(
```
Comment (rudeUltra) [inline server/src/modules/data-sources/util.service.ts]: move this to helpers

File: server/src/modules/data-sources/util.service.ts [hunk 5]
```diff
@@ -936,12 +1005,73 @@ export class DataSourcesUtilService implements IDataSourcesUtilService {
     }
   }
 
-  async getAuthUrl(getDataSourceOauthUrlDto: GetDataSourceOauthUrlDto): Promise<{ url: string }> {
-    const { provider, source_options = {}, plugin_id = null } = getDataSourceOauthUrlDto;
+  async getAuthUrl(getDataSourceOauthUrlDto: GetDataSourceOauthUrlDto, user?: User): Promise<{ url: string }> {
```
Comment (rudeUltra) [inline server/src/modules/data-sources/util.service.ts]: fetch from DTO itself

File: server/src/modules/data-sources/util.service.ts [hunk 6]
```diff
@@ -936,12 +1005,73 @@ export class DataSourcesUtilService implements IDataSourcesUtilService {
...
+      return { url: service.authUrl(resolvedSourceOptions) };
+    }
+
     return { url: service.authUrl(source_options) };
   }
 
+  /**
+   * Resolves workspace constants in source options for OAuth flows generating auth URLs.
+   */
+  protected async resolveSourceOptionsForOAuth(
```
Comment (rudeUltra) [inline server/src/modules/data-sources/util.service.ts]: move this to helper aswell

File: frontend/src/_services/datasource.service.js [hunk 7]
```diff
@@ -95,8 +95,13 @@ function setOauth2Token(dataSourceId, body, current_organization_id) {
...
 }
 
-function fetchOauth2BaseUrl(provider, plugin_id = null, source_options = {}) {
-  const payload = { provider, ...(plugin_id && { plugin_id }), ...(source_options && { source_options }) };
+function fetchOauth2BaseUrl(provider, plugin_id = null, source_options = {}, environment_id = null) {
+  const payload = { 
+    provider, 
+    ...(plugin_id && { plugin_id }), 
+    ...(source_options && { source_options }),
+    ...(environment_id && { environment_id })
```
Comment (rudeUltra) [inline frontend/src/_services/datasource.service.js]: pass org_id here as well and use it in the services, no need of User decorator

File: server/src/modules/data-sources/util.service.ts [hunk 8]
```diff
@@ -937,8 +979,24 @@ export class DataSourcesUtilService implements IDataSourcesUtilService {
...
 
   async getAuthUrl(getDataSourceOauthUrlDto: GetDataSourceOauthUrlDto): Promise<{ url: string }> {
-    const { provider, source_options = {}, plugin_id = null } = getDataSourceOauthUrlDto;
+    const { provider, source_options = {}, plugin_id = null, environment_id, organization_id } = getDataSourceOauthUrlDto;
     const service = await this.pluginsServiceSelector.getService(plugin_id || null, provider);
+
+    if (organization_id) {
+      let envId = environment_id;
+      if (!envId) {
+        const defaultEnv = await this.appEnvironmentUtilService.get(organization_id, null, true);
```
Comment (rudeUltra) [inline server/src/modules/data-sources/util.service.ts]: If orgId or envId not present then just skip resolving, no need to fetch the default one

**Review by rudeUltra — APPROVED** [review]

File: server/src/modules/data-sources/util.service.ts (hunk 3 above)
Comment (sahil7303) [reply server/src/modules/data-sources/util.service.ts:157]: Confirmed, existing options is not getting overriden
