### PR TITLE
[fix] Incorrect edit informations is displayed on app card

### LINKED ISSUE #5554: [Dashboard screen]- Incorrect edit informations is displayed
### What is the expected behaviour?

If user is editing the existing application, the last edit information displayed on dashboard should reflect the same.
e.g. if user has created an application 4 days ago and making some edits today, the information should be displayed as follows:
"Edited 2 hours ago by XYZ"

### What is the current behaviour?

  Instead of showing the latest updates specific information, system is showing the application created time as:
"Edited 4 days ago by XYZ"

### How to reproduce the issue?

1. create an application and verify the default information on dashboard
2. edit the application later and verify the same information
3. information should reflect the latest changes

### PR DESCRIPTION
**Pull request by shah21**
Resolves #5554

### CODE REVIEW

File: frontend/src/HomePage/AppCard.jsx [hunk 1]
```diff
@@ -52,7 +52,8 @@ export default function AppCard({
     // eslint-disable-next-line react-hooks/exhaustive-deps
   }, [isHovered]);
 
-  const updated = moment(app.created_at).fromNow(true);
+  const updated_at = app?.editing_version?.updated_at || app?.updated_at;
```
Comment (gsmithun4) [inline frontend/src/HomePage/AppCard.jsx:55]: Question: are we showing last updated user?
Shows in UI that
updated just now by `A`.
where `A` is app created user, and recently edited by other user

**Review by gsmithun4 — CHANGES_REQUESTED** [review]

File: frontend/src/HomePage/AppCard.jsx (hunk 1 above)
Comment (shah21) [reply frontend/src/HomePage/AppCard.jsx:55]: @thehacklady

**Review by gsmithun4 — APPROVED** [review]
