### PR TITLE
Fix: Center alignment icon of text widget's alignment property is different color in dark mode 

### LINKED ISSUE #1876: Center alignment icon of text widget's alignment property is different color in dark mode
### Version Information
Latest

### Environment

MacOs
### What is the expected behaviour?

All icons of text alignment buttons should be unique in the dark mode

### What is the current behaviour?

The Center icon's color is different in the dark mode 
### Screenshots or Screencast

Screenshot 2022-01-20 at 10 51 00 AM

### If the bug is confirmed, would you be willing to submit a PR?
Yes

### PR DESCRIPTION
**Pull request by shah21**
Fixes #1876

### CODE REVIEW

File: frontend/src/Editor/Inspector/Elements/AlignButtons.jsx [hunk 1]
```diff
@@ -51,7 +51,7 @@ export const AlignButtons = ({ param, definition, onChange, paramType, component
               viewBox="0 0 16 16"
               fill="none"
               xmlns="http://www.w3.org/2000/svg"
-              className="svg-icon"
+              // className="svg-icon"
```
Comment (Navaneeth-pk) [inline frontend/src/Editor/Inspector/Elements/AlignButtons.jsx:54]: Remove the line if it is not needed.

Comment (shah21) [reply frontend/src/Editor/Inspector/Elements/AlignButtons.jsx:54]: sure

**Review by Navaneeth-pk — APPROVED** [review]
