### PR TITLE
[HF23-AB]Enter to Delete | Closes #7711

### LINKED ISSUE #7711: Pressing enter/return key should delete the component
### What is the expected behaviour?

When the confirmation modal for deleting the component pops up, the user should be able to provide input `Yes` by pressing the `Enter/return` key or `Cancel` using the `Esc` key. 

### What is the current behaviour?

Currently, the user will have to use the mouse click to select the option.

### How to reproduce the issue?

1. Drag a component onto the canvas
2. Use `delete` button (windows/linux) or `back` (mac) to delete the component
3. The confirmation modal will popup
4. Try pressing `Enter` or `return` 

### Screenshots or Screencast
Screenshot 2023-10-09 at 4 57 35 PM

### PR DESCRIPTION
**Pull request by NotTheRightGuy**
Added to functionality to delete components when Confirmation modal is open using Enter/Return key.

fixes #7711

### CODE REVIEW

File: frontend/src/Editor/Inspector/Inspector.jsx [hunk 1]
```diff
@@ -382,15 +382,31 @@ export const Inspector = ({
     // eslint-disable-next-line react-hooks/exhaustive-deps
   }, [JSON.stringify({ showHeaderActionsMenu })]);
 
+  const handleDeleteConfirm = () => {
```
Comment (nakulnagargade) [inline frontend/src/Editor/Inspector/Inspector.jsx:385]: @NotTheRightGuy Can you please wrap this handleDeleteConfirm inside a callback like below since eslint is throwing a warning error. This is because on every render, a new handleDeleteConfirm function will be created but then its is a useEffect dependency as well hence the warning. Else the PR looks good.

const handleDeleteConfirm = useCallback(() => {
    switchSidebarTab(2);
    removeComponent(component);
    setWidgetDeleteConfirmation(false);
  }, [switchSidebarTab, removeComponent, component]);

Comment (NotTheRightGuy) [reply frontend/src/Editor/Inspector/Inspector.jsx]: I have wrapped the function in a callback. Please let me know if anything else needs to be changed.

**Comment by nakulnagargade** [comment]
@NotTheRightGuy Approving the PR. Please do resolve the conflict.

**Review by nakulnagargade — APPROVED** [review]

**Comment by NotTheRightGuy** [comment]
> @NotTheRightGuy Approving the PR. Please do resolve the conflict.

I have resolved the conflict. Please merge if everything looks good.

**Review by nakulnagargade — APPROVED** [review]

**Comment by Nandinisaha13** [comment]
Hi @NotTheRightGuy can you please check the code, I can see the whole application crashing while I drop any component, attaching a video with console errors. 
cc: @kavinvenkatachalam @tejakummarikuntla @nakulnagargade 

https://github.com/ToolJet/ToolJet/assets/41302917/6c2c63f6-fa55-4aeb-b898-32cda5a2fe46

**Comment by NotTheRightGuy** [comment]
> Hi @NotTheRightGuy can you please check the code, I can see the whole application crashing while I drop any component, attaching a video with console errors. cc: @kavinvenkatachalam @tejakummarikuntla @nakulnagargade
> 
>  Screen.Recording.2023-10-26.at.11.00.54.AM.mov

Sorry for my mistake. Because useCallback() isn't imported it was throwing that error. Now using React.callBack() instead. Hope it fixes the error now.

**Review by nakulnagargade — APPROVED** [review]
