### PR TITLE
[hotfix] : Fix typing delay in text input and textarea

### LINKED ISSUE #10481: Runjs on form submit, input values are cleared before the runjs execution take place.

### PR DESCRIPTION
**Pull request by nakulnagargade**
This fixes 

1. Typing too fast in textinput and textarea would cause delay.
2. In dropdown, the defaultvalue is not working when its a number
3. [Runjs on form submit, input values are cleared before the runjs execution take place

Resolves #10481, #10480, #10479

### CODE REVIEW

File: frontend/src/Editor/Components/TextArea.jsx [hunk 1]
```diff
@@ -28,13 +29,22 @@ export const TextArea = function TextArea({
...
+  const debouncedOnChange = useCallback(
+    debounce((value) => {
+      setExposedVariable('value', value);
+    }, 0),
+    []
+  );
+
+  const onChange = (e) => {
+    setValue(e.target.value);
+    debouncedOnChange(e.target.value);
```
Comment (TooljetBot) [inline frontend/src/Editor/Components/TextArea.jsx:41]: <div>

<strong>Bito Code Review Agent Run</strong> <a href=https://github.com/ToolJet/ToolJet/pull/10463#issuecomment-2250192404>#092189</a><span> - 07/25/2024, 12:23 pm</span>
<br>

<div><small>🔴</small> High importance</div>

<div id="suggestion">
<div id="issue">
<b>Issue:</b> The debounce delay is set to 0, which effectively disables debouncing. This might not solve the typing delay issue effectively.
</div>
<div id="fix">
<b>Fix:</b> Increase the debounce delay to a reasonable value (e.g., 300ms) to effectively reduce the frequency of setExposedVariable calls and prevent UI freezing.
</div>
<details>
<summary>
<b>Code suggestion</b>
</summary>
<div id="code">

```
 @@ -35,7 +35,7 @@
   setExposedVariable('value', value);
 }, 0),
 [],
 );
 + }, 300),
 + [],
 + );
```
</div>
</details>
</div>
<br>


</div>

Is this a valid issue, or was it incorrectly flagged by the Agent?
- [ ] it was incorrectly flagged

File: frontend/src/Editor/Components/TextInput.jsx [hunk 2]
```diff
@@ -241,6 +242,19 @@ export const TextInput = function TextInput({
...
+      fireEvent('onChange');
+    }, 0),
+    []
+  );
+
+  const onChange = (e) => {
+    setValue(e.target.value);
+    debouncedOnChange(e.target.value);
+  };
+
```
Comment (TooljetBot) [inline frontend/src/Editor/Components/TextInput.jsx:257]: <div>

<strong>Bito Code Review Agent Run</strong> <a href=https://github.com/ToolJet/ToolJet/pull/10463#issuecomment-2250192404>#092189</a><span> - 07/25/2024, 12:23 pm</span>
<br>

<div><small>🔴</small> High importance</div>

<div id="suggestion">
<div id="issue">
<b>Issue:</b> The 'debouncedOnChange' function is created using 'useCallback' with an empty dependency array. This means the function will be memoized only once and will not update if any dependencies change. If 'setExposedVariable' or 'fireEvent' functions change, the 'debouncedOnChange' function will not reflect those changes, potentially leading to stale closures.
</div>
<div id="fix">
<b>Fix:</b> Add 'setExposedVariable' and 'fireEvent' as dependencies to the 'useCallback' hook to ensure that the 'debouncedOnChange' function is updated if these functions change.
</div>
<details>
<summary>
<b>Code suggestion</b>
</summary>
<div id="code">

```
 @@ -250,6 +250,6 @@
     []
   );

   const onChange = (e) => {
     setValue(e.target.value);
     debouncedOnChange(e.target.value);
   };
 +  }, [setExposedVariable, fireEvent]);
 +  );
 +
 +  const onChange = (e) => {
 +    setValue(e.target.value);
 +    debouncedOnChange(e.target.value);
 +  };
```
</div>
</details>
</div>
<br>


</div>

Is this a valid issue, or was it incorrectly flagged by the Agent?
- [ ] it was incorrectly flagged

**Review by johnsoncherian — DISMISSED** [review]

**Review by johnsoncherian — APPROVED** [review]

**Review by johnsoncherian — APPROVED** [review]
