### PR TITLE
Bugfix: Scrolling is broken for code editor on postgresql query manager

### LINKED ISSUE #1546: Scrolling is broken for code editor on postgresql query manager
### Environment

Enterprise deployment, Ubuntu 20.04
### What is the expected behaviour?

When a user scrolls down inside the code editor of PostgreSQL query manager, the code inside the editor should scroll, instead of the whole query manager.
### What is the current behaviour?

When a user scrolls down inside the code editor of PostgreSQL query manager, the code inside the editor should scroll, instead the whole query manager is scrolling.
### How to reproduce the issue?

1. Create a postgres query
2. Type in more code than will fit in the code hinter
3. Try to scroll down to see the remaining code

### Screenshots or Screencast

scroll-psql-manager

### PR DESCRIPTION
**Pull request by arpitnath**
Fixes #1546 

**Loom**: https://www.loom.com/share/184d43381df046dca3d8089efe120612

### CODE REVIEW

File: frontend/src/Editor/CodeBuilder/CodeHinter.jsx [hunk 1]
```diff
@@ -34,6 +34,7 @@ export function CodeHinter({
   lineWrapping,
   componentName = null,
   usePortalEditor = true,
+  isScrollable = false,
```
Comment (gondar00) [inline frontend/src/Editor/CodeBuilder/CodeHinter.jsx:37]:
```suggestion
  className = 'code-hinter,
```

File: frontend/src/Editor/QueryManager/QueryEditors/Postgresql.schema.json [hunk 2]
```diff
@@ -23,7 +23,8 @@
         "$key": "query",
         "type": "codehinter",
         "description": "Enter query",
-        "height": "150px"
+        "height": "150px",
+        "isScrollable": true
```
Comment (gondar00) [inline frontend/src/Editor/QueryManager/QueryEditors/Postgresql.schema.json:27]:
```suggestion
        "className": ""
```

**Review by gondar00 — CHANGES_REQUESTED** [review]
Let's use className istead of isScrollable

**Review by sherfin94 — DISMISSED** [review]

**Review by gondar00 — APPROVED** [review]
