### PR TITLE
Hot fixed : app is crashing upon clicking on codehinter icon in isEditable field in table column

### LINKED ISSUE #6509: App is getting crashed upon clicking on codehinter expand icon in isEditable field in table column
### Environment
Cloud

### What is the expected behaviour?
Upon clicking on the code-hinter expand icon in table columns for isEditable field, it should open the code-hinter pop-up

### What is the current behaviour?
Upon clicking on the code-hinter expand icon in table columns for isEditable field, the app is crashing

### How to reproduce the issue?

1. Open new application
2. Drag a Table component from the right sidebar on the canvas
3. Click on the component on the canvas to open the component inspector in the right sidebar
4. In the table inspector, look for the column section inside the properties tab
5. Open any one of the available columns by clicking on the respective card in the column section
6. A pop-up window will appear to the left of the card, inside the pop-up at the bottom look for the make editable field and press the fx button corresponding to the same field.
7. A code-hinter will be showing up instead of a toggle switch, hover on the code-hinter, inside the code-hinter to its right, you will see one icon to expand the code-hinter, please click on it, the app will crash

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/37823141/babdb1c9-c5ca-4063-ad36-e9bb4c1eaac6

### If the bug is confirmed, would you be willing to submit a PR?
Yes

### PR DESCRIPTION
**Pull request by manishkushare**
Resolves #6509

### CODE REVIEW

File: frontend/src/Editor/Inspector/Components/Table/ProgramaticallyHandleToggleSwitch.jsx [hunk 1]
```diff
@@ -18,28 +19,29 @@ export const ProgramaticallyHandleToggleSwitch = ({
...
+    <div className={`mb-2 field ${options.className}`} onClick={(e) => e.stopPropagation()}>
+      <CodeHinter
+        enablePreview={true}
+        currentState={currentState}
+        initialValue={initialValue}
+        mode={options.mode}
+        theme={darkMode ? 'monokai' : options.theme}
+        lineWrapping={true}
+        onChange={(value) => callbackFunction(index, property, value)}
+        componentName={`widget/${component.component.name}::${param.name}`}
```
Comment (johnsoncherian) [inline frontend/src/Editor/Inspector/Components/Table/ProgramaticallyHandleToggleSwitch.jsx:33]: I think we should check if the parent object is empty since we are pulling out a nested attribute
eg: `component?.component?.name` or use lodash `get` method

**Review by johnsoncherian — APPROVED** [review]

**Review by johnsoncherian — APPROVED** [review]
