### PR TITLE
fixed: Improper date parsing

### LINKED ISSUE #1309: Improper date parsing
### Version 
0.8.0

### Environment

Docker
### What is the expected behaviour?

GraphQL date data is sent in 'YYYY-MM-DD' format, and on table, using the 'date picker' column type option, date should appear accordingly 

### What is the current behaviour?

Rather than YYYY-MM-DD format, it seems to be parsing the data as DD-MM-YYYY

### How to reproduce the issue?

1. Create a postgres with a date column
2. enter dates in YYYY-MM-DD format
3. Use the Postgres as data source
4. Create a table component in tooljet, create a column type for `date picker`. 
5. display the date column

### Screenshots or Screencast

Screenshot 2021-10-26 165406
data represented in YYYY-MM-DD in postgres
Screenshot 2021-10-26 165304
under queries, it was fetched accordingly
image
data is parsed improperly

### Any possible solutions?
would be nice to provide option for users to parse the data 
image
Similar to how the application provides option for users to display the parsed data, 
users can enter how the date data is parsed as well 

### If the bug is confirmed, would you be willing to submit a PR?
no, sorry! 😞

### PR DESCRIPTION
**Pull request by arpitnath**
Fixes #1309 

**Loom** - https://www.loom.com/share/23fc6e0ae5904392a59845bd2c9090b3

### CODE REVIEW

**Comment by sherfin94** [comment]
Hey man! there seem to be some issues. The displayed date is not changing when I change the value on the inspector.
date-not-changing-when-edited

**Comment by sherfin94** [comment]
Show-time feature is not working at times, this happens once I changed values by editing on the inspector. It did work once I turned 'Make editable' on.
show-time
.

File: frontend/src/Editor/Components/Table/Datepicker.jsx [hunk 1]
```diff
@@ -5,36 +5,46 @@ import moment from 'moment';
...
-  const dateChange = (e) => {
-    if (isTimeChecked) {
-      setDate(e.format(`${dateFormat} LT`));
-    } else {
-      setDate(e.format(dateFormat));
-    }
+const getDate = (value, parseDateFormat, displayFormat) => {
+  const dateString = value;
+  const momentObj = moment(dateString, parseDateFormat);
+  console.log('parsedDateObj', momentObj);
```
Comment (sherfin94) [inline frontend/src/Editor/Components/Table/Datepicker.jsx:11]:
```suggestion
```

**Review by sherfin94 — CHANGES_REQUESTED** [review]
Can we also change the text 'Date format' to 'Date display format'?

**Review by sherfin94 — APPROVED** [review]
