### PR TITLE
Fixed page options clicks issue

### LINKED ISSUE #7394: Page options clicks are not working when we hard click it with the trackpad.
### What is the expected behaviour?

  Page options clicks needs to work on both soft click and hard click with trackpad.

### What is the current behaviour?

Page options clicks are not working in hard click, it works only in soft click.

### How to reproduce the issue?

1. Create App, add one or more pages.
2. Click on three dots and try to hard click rename or delete or any options with Trackpad.
3. you can see the issue with hard click.

### PR DESCRIPTION
**Pull request by S-Abdul-Rahman**
Fixed #7394

### CODE REVIEW

File: frontend/src/Editor/LeftSidebar/SidebarPageSelector/PagehandlerMenu.jsx [hunk 1]
```diff
@@ -154,14 +154,15 @@ const PageHandleField = ({ page, updatePageHandle }) => {
...
+    e.preventDefault()
     e.stopPropagation();
     closeMenu();
     callback(id);
   };
 
   return (
     <div className={`field ${customClass ? ` ${customClass}` : ''}`}>
-      <Button.UnstyledButton onClick={handleOnClick} styles={{ height: '28px' }} disabled={disabled}>
+      <Button.UnstyledButton onMouseDown={handleOnClick} onClick={handleOnClick} styles={{ height: '28px' }} disabled={disabled}>
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/LeftSidebar/SidebarPageSelector/PagehandlerMenu.jsx:165]:
```suggestion
      <Button.UnstyledButton onClick={handleOnClick} styles={{ height: '28px' }} disabled={disabled}>
```

File: frontend/src/Editor/LeftSidebar/SidebarPageSelector/RenameInput.jsx [hunk 2]
```diff
@@ -4,8 +4,12 @@ export const RenameInput = ({ page, updaterCallback, updatePageEditMode }) => {
   const handleAddingNewPage = (pageName) => {
     if (pageName.length > 0 && pageName !== page.name) {
       updaterCallback(page.id, pageName);
+      updatePageEditMode(false);
+    } else {
+      //updaterCallback(page.id, pageName);
+      updatePageEditMode(false);
     }
-    updatePageEditMode(false);
+
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/LeftSidebar/SidebarPageSelector/RenameInput.jsx:12]: This can be reverted. Both works in the same way

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@S-Abdul-Rahman Request a few changes. Please take a look

**Review by kavinvenkatachalam — APPROVED** [review]
