### PR TITLE
bug fixed : The result of the previous previewed query remains

### LINKED ISSUE #2827: The result of the previous previewed query remains
### Environment
MacOS 12.3.1

### What is the expected behaviour?
The preview pane shows the result of the previously previewed query

### What is the current behaviour?
when the query gets deleted (because you clicked the plus button again, without saving the previous query), the preview panel should also be cleared

### How to reproduce the issue?

1. Create a REST api datasource with this endpoint: `https://reqres.in/`
2. Click the + button in the Queries panel to create a new query
3. Add this path to the datasource url: `api/users`
4. Click the preview button
5. Notice the results of the query in the preview panel
6. Click the + button again without saving the query
7. Notice the path input gets cleared, but the preview panel still shows the result of the previous query

### Screenshots or Screencast

https://user-images.githubusercontent.com/1907152/163372131-d7ca1ce5-e652-4560-ae3f-481a4f3558d4.mov

### If the bug is confirmed, would you be willing to submit a PR?
No

### PR DESCRIPTION
**Pull request by manishkushare**
Resolves #2827

### CODE REVIEW

**Comment by shubh22** [comment]
Task linked: [CU-2vd8ffd The result of the previous previewed query remains](https://app.clickup.com/t/2vd8ffd)

File: frontend/src/Editor/QueryManager/QueryManager.jsx [hunk 1]
```diff
@@ -413,7 +416,15 @@ class QueryManagerComponent extends React.Component {
...
-
+    console.log(
+      'selectedDataSource',
+      selectedDataSource,
+      'selectedQuery',
+      selectedQuery,
+      'queryPreviewData',
+      queryPreviewData,
+      'query'
+    );
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/QueryManager/QueryManager.jsx:427]:
```suggestion
```

File: frontend/src/Editor/QueryManager/QueryManager.jsx [hunk 2]
```diff
@@ -159,6 +159,9 @@ class QueryManagerComponent extends React.Component {
     //     }
     //   }
     // }
+    if (this.state.selectedQuery?.id !== nextProps.selectedQuery?.id) {
+      this.setState({ queryPreviewData: undefined });
+    }
```
Comment (kavinvenkatachalam) [inline frontend/src/Editor/QueryManager/QueryManager.jsx:164]:
```suggestion
```

Instead of setting state in `componentWillReceiveProps`, set it in `setStateFromProps` where we set all the other states. It will avoid the one cycle of re-render. 

`queryPreviewData:
          this.state.selectedQuery?.id !== props.selectedQuery?.id ? undefined : this.state.queryPreviewData,`

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@manishkushare Added a few suggestions.

**Review by kavinvenkatachalam — APPROVED** [review]
